### ISSUE TITLE
Can "RE-flex" be used as a full drop-in replacement for "flex"?

### ISSUE THREAD

**Issue by firasuke** [Genivia/RE-flex#102]
As the title states, can `RE-flex` fully replace `flex`?

**Comment by genivia-inc** [comment]
Yes, but only for C++ projects as the description says. To do so use option `--flex`. I've tested RE/flex dozens of Flex projects. We and others have converted Flex projects to RE/flex.

**Comment by firasuke** [comment]
If I understood correctly, and from a Linux distribution developer point of view, I have to use both `flex` and `RE-flex` to cover for both C and C++ lexing, am I right? Or is there something I'm missing here?

Also, are there plans to cover C lexing as well, to make `RE-flex` truly a full drop-in replacement for `flex`?

**Comment by genivia-inc** [comment]
> If I understood correctly, and from a Linux distribution developer point of view, I have to use both flex and RE-flex to cover for both C and C++ lexing, am I right? Or is there something I'm missing here?

To cover C scanning/lexing applications please use Flex. But you will miss out on many new features added to RE/flex. Most C projects rather trivially convert to C++ anyway. The old C++ standard was rather specific about this. So you can use RE/flex with C projects, but compiled as C++ which is almost always compilable with older C code (e.g. a few rather arcane const pointer syntax rules are different between C and C++).

RE/flex is a replacement of `flex++` as the doc says and accepts Flex lexer specs. Note the `flex++` has been broken for many years, e.g. try something as simple as `--main` and it won't work. The trouble with `flex++` is mentioned in Levine's excellent textbook. For that reason and other such as teaching Compiler Construction for 20 years explaining limitation of Flex, was the breaking point for me to produce a more usable upgrade.

**Comment by genivia-inc** [comment]
So to answer your question succinctly: no, you do not need Flex any longer (assuming C++ is not a challenge to use).

**Comment by firasuke** [comment]
Thanks for your time and effort!
