### ISSUE TITLE
Character class operations with named Unicode patterns

### ISSUE THREAD

**Issue by thorsten-fluegel** [Genivia/RE-flex#103]
For the (incomplete) GenericTokenChar rule from the PowerShell language specification [1] an error is raised about a malformed regular expression or unsupported syntax:
```%option unicode

lower     [a-z]
upper     [A-Z]
letter    {lower}{|}{upper}

DoubleQuote ["\u{201c}\u{201d}\u{201e}]
GenericTokenChar [^{}();,|&$]{-}{DoubleQuote}

%%

{letter}+
{GenericTokenChar}+

%%
```
gives this error:
```
[^{}();,|&$]{-}{DoubleQuote}
                           \___invalid character class range
```

The syntax works in the letter rule unless a Unicode character is added to either the upper or lower rule.
From what I understand character classes are indeed restricted to ASCII in the bracket notation.

However it seems to work with Unicode if the defined names are expanded:
```
%option unicode
%option debug
%option main

lower     [a-z]
upper     [A-Z]
letter    {lower}{|}{upper}

ExpandedGenTokenChar [^{}();,|&$]{-}["\u{201c}\u{201d}\u{201e}]

%%

{letter}+
{ExpandedGenTokenChar}+

%%
```
eats up the entire input file except for e.g. braces `{}` or ASCII or Unicode quotation marks `"`, which are printed as expected.

It would be desirable to be able to use this feature even with Unicode characters in such a class as it greatly improves the readability of the rules. At least an easier to understand message should be printed (why is it invalid?).

[1] Windows PowerShell Language Specification Version 3.0, https://www.microsoft.com/en-us/download/details.aspx?id=36389

**Comment by genivia-inc** [comment]
Thanks for the feedback.

This matter was discussed before, see #55. We settled on a documented limitation of the `{+}`, `{-}`, `||`, `--` etc operators to support ASCII and 8bit patterns only for defined names `{name}`. The RE/flex manual mentions this limitation:

>   Pattern            | Matches
>   ------------------ | --------------------------------------------------------
>   `[a-z]{+}[A-Z]`    | matches a letter, same as `[a-z￨￨[A-Z]]`
>   `[a-z]{￨}[A-Z]`    | matches a letter, same as `[a-z￨￨[A-Z]]`
>   `[a-z]{&}[^aeiou]` | matches a consonant, same as `[a-z&&[^aeiou]]`
>   `[a-z]{-}[aeiou]`  | matches a consonant, same as `[a-z−−[aeiou]]`
> 
> Multiple operators can be chained together.  Unlike Flex, defined names may be
> used as operands.  For example `{lower}{+}{upper}` is the same as
> `[a-z]{+}[A-Z]`, i.e. the character class `[A-Za-z]`.  **A defined name when used
> as an operand should expand into a POSIX character class containing ASCII
> characters only.**

The behavior is still compatible with Flex (i.e. limited to ASCII or 8-bit), but cannot be easily extended to support Unicode unfortunately.

Because this is only a minor esthetic issue, this will not be addressed any time soon.

**Comment by thorsten-fluegel** [comment]
Ah, I somehow missed that issue. If it's really that complicated to fix then I can live with that, Re/flex is anyway far better than Flex, and also a lot faster. Thanks for this great tool!
