### ISSUE TITLE
Erroneous extra chars in UTF16LE files

### ISSUE THREAD

**Issue by thorsten-fluegel** [Genivia/RE-flex#104]
In UTF16LE files with BOM three extra characters are passed to the lexer after the first character, leading to a wrong lexer output for the file.

If the input is just "line" and we take a simple word-rule that matches on {letter}+, the rule matches twice and the input is split into "l" and "ine", separated by three null characters that are matched by the default rule and are printed.

I.e. this lexer file:
```
%option unicode
%option debug
%option main

lower     [a-z]
upper     [A-Z]
letter    {lower}{|}{upper}

%%

{letter}+

%%
```

compiled on cygwin with gcc 10.2 using
```
reflex min.ll && g++ lex.yy.cpp -I $REFLEX/include $REFLEX/lib/libreflex.a
```

leads to this output:
```
--rule min.ll:11 start(0) 1,0:"l"
--default rule
\0--default rule
\0--default rule
\0--rule min.ll:11 start(0) 1,4:"ine"
--EOF start(0)
```
_(there's a linefeed \x0A after "l" and "ine", the default rules are followed by linefeeds \x0A and a null character \x00)_

when running
```
cat test_u16le.txt | a.exe 2>&1
```

This doesn't happen with UTF16BE file with BOM however, or with UTF8 with or without BOM.
Then "line" is matched by the rule from the lexer file as expected.

**Comment by genivia-inc** [comment]
Thanks for the feedback! While we do a lot of testing, but this issue with UTF-16LE appears to have passed under the radar, so we'll add more test cases and updated RE/flex accordingly.

**Comment by genivia-inc** [comment]
File `lib/input.cpp` line 718 should be:
~~~
                ulen_ = 1;
~~~
Looks like a typo to me. The value was 4, but only one byte should be retained after checking four bytes with a BOM.

**Comment by thorsten-fluegel** [comment]
Yep, this fixes the issue. Thanks!
