### ISSUE TITLE
Missing flex function?

### ISSUE THREAD

**Issue by Eidonko** [Genivia/RE-flex#109]
Hello,
I am trying to use reflex as a flex-with-unicode-support. I have compiled reflex on my ubuntu 21.04 machine. 
I compiled my flex file, "tree2nodot.l", with "reflex --flex --bison --graphs-file  tree2nodot.l"
Then I tried to compile the resulting code with "c++ -o tree2nodot lex.yy.cpp -L/usr/local/lib -lreflex"
This resulted in the following errors:
tree2nodot.l: In function ‘int till_eol()’:
tree2nodot.l:10:15: error: ‘input’ was not declared in this scope
   10 |  while ( (c = input()) != EOF ) {
      |               ^~~~~

Is there an equivalent of function input() in reflex, such that I may getc a character from the standard input stream?
Thank you very much,
kind regards,
Eidonko

**Comment by genivia-inc** [comment]
The function is `yyinput()` in Flex.

**Comment by Eidonko** [comment]
Thank you!

-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Jul 16, 2021, 17:43 by ***@***.***:

**Comment by Eidonko** [comment]
Hi,

I tried using yyinput() and I get this error:

tree2nodot.l:10:15: error: ‘YY_SCANNER’ was not declared in this scope
   10 |  while ( (c = yyinput()) != EOF ) {
      |               ^~~~~~~

Shall I send you the whole source code?

Thank you for your help, cheers
Eidon

-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Jul 16, 2021, 17:43 by ***@***.***:

**Comment by genivia-inc** [comment]
There is no global scanner object (`YY_SCANNER`). Using `yyinput()` outside the scanner's scope will produce an error. Because the default is to produce a C++ scanner class, all functions should be invoked within the scope of this class (i.e. `YY_SCANNER` is `this`). Create a static global scanner instead with option `--bison` to force global functions (which is not thread safe) instead of a nice C++ scanner class.

**Comment by genivia-inc** [comment]
The RE/flex manual:
#### `−−bison`

This option generates a scanner that works with Bison parsers, by defining
global (i.e. non-thread-safe and non-reentrant) "yy" variables and functions,
such as `yytext`, `yyleng`, `yylineno`, and `yylex()`.  See reflex-bison
for more details.  Use option `−−noyywrap` to remove the dependency on the
global `yywrap()` function.  Use option `−−bison-locations` to support the
Bison <i>`%locations`</i> feature.  See also the `−−yy` option.

I've added a comment to the updated documentation to avoid confusion about this in the future: https://www.genivia.com/doc/reflex/html/index.html#yy-functions

**Comment by Eidonko** [comment]
thanks!

-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Jul 19, 2021, 18:24 by ***@***.***:
