### ISSUE TITLE
Why is `REFLEX_OPTION_*` only undefined at the top of the header when a prefix is specified?

### ISSUE THREAD

**Issue by jafl** [Genivia/RE-flex#114]
It seems like it should always be undefined, even without a prefix?

**Comment by genivia-inc** [comment]
It's undef-ing when the --prefix option is specified. It should also undef when the --namespace option is specified. I think that is what is missing.

**Comment by jafl** [comment]
Yes, that would work.  Would you like me to generate a PR?

**Comment by genivia-inc** [comment]
I've already made the change and will release 3.0.11 later today pending the answer to the other issue.
