### ISSUE TITLE
FlexLexer and --params option issue

### ISSUE THREAD

**Issue by atlant10** [Genivia/RE-flex#117]
Hello

Trying to migrate from flex-bison to reflex-bison, using reflex 3.0.1 or 3.0.11 and bison 3.7.5 on macos 10.15.

I have 2 test projects, both based on reflexexample11.lxx (and .yxx), that is
--bison-complete --bison-locations
 
Both scanners should take an extra parameter. When using options
--flex --params="TYPE NAME"
the scanner can't be constructed. The call
yy::scanner scanner(text);
gives buildtime error
Variable type 'yy::scanner' is an abstract class
Unimplemented pure virtual method 'yylex' in 'scanner'

The second analogous project with option
--params="TYPE NAME"
using the AbstractLexer class works well.
 
How can I generate a FlexLexer which takes an additional parameter, i.e. options --flex and --params="TYPE NAME"?

**Comment by genivia-inc** [comment]
Fixed in 3.0.12.

**Comment by genivia-inc** [comment]
The update inserts the missing `yylex()` function if `--params=` or `%params=` is used with `--flex`. I ran a check and this fixed the problem for me for this issue`:

> gives buildtime error
> Variable type 'yy::scanner' is an abstract class
> Unimplemented pure virtual method 'yylex' in 'scanner'

I didn't see the attachment or details of the (other?) issue.

**Comment by atlant10** [comment]
Hello Robert

Refering to the problem with --bison.complete --flex and --params options. I reviewed the code in Re/flex 3.0.12 /src/reflex.cpp and found out why it does not work (for me):

line 2146:
    if (!options["bison_complete"].empty()) {
line 2162-3:
      *out <<
        "  virtual " << token_type << " " << lex << "(" << params << ")";
line 2164:
    }
line 2165-2217:
    else if's { } (other bison-xx options)
line 2226-44:
    else { } (not executed because of 2146)

As lines 2146-64 are executed, line 2135 is never executed. Therefore the 
"  virtual " << token_type << " yylex(void)\n" ...
function in line 2135ff. is not written to *out.

I have confirmed this code path with lldb and fixed my reflex.cpp. Now it works.

***@***.*** ***@***.***>

**Comment by genivia-inc** [comment]
Fixed in 3.1.0.

**Comment by atlant10** [comment]
Hi Robert

Thanks for the update. There seems to be a little glitch in reflex.cpp (3.1.0), line 2173, which reads

"    LexerError(\"" << lexer << "::yylex invoked but %option params=\"" << params << "\" is used\");\n"

My generated scanner file looks like

LexerError("expr_scanner::yylex invoked but %option params="pctx_ptr yyextra" is used");

The compiler complains about this. Using the template

"    LexerError(\"" << lexer << "::yylex invoked but %option params=\\\"" << params << "\\\" is used\");\n"

generates a correct scanner file.

Thanks again,
--vk

**Comment by genivia-inc** [comment]
Whoops, thanks for pointing this out. There are two lines that need two `\\` escapes each: 2173 and 2253.
