### ISSUE TITLE
Custom namespace and class name not supported in bison-cc

### ISSUE THREAD

**Issue by Krantz-XRF** [Genivia/RE-flex#12]
In Bison, we may rename the default namespace `yy` and the default class name `parser`, but option bison-cc has hard-coded the name as `yy` and `parser`, currently I can workaround this by manually rename these in the generated files, or use the default names in bison. 

It works if I `#define` `yy` and `parser` to something else, but I guess it would be better to support this in RE/flex.

**Comment by genivia-inc** [comment]
Done. Download version 1.0.7.
