### ISSUE TITLE
How is RE-flex different from reflex?

### ISSUE THREAD

**Issue by firasuke** [Genivia/RE-flex#120]
There exists a project with a similar name that appears to be a variant of flex as well:

https://invisible-island.net/reflex/

**Comment by genivia-inc** [comment]
When releasing RE/flex back in 2016, I searched the web for "reflex" with flex but could not find any public distros and repos that matched both names with the project name being "reflex". Anyway, RE/flex is the official name of this project, suggesting a combination of "RE" (regular expression libraries) with "flex". So I don't see a problem.
