### ISSUE TITLE
Injected Lexer class members of type reference cannot be initialized

### ISSUE THREAD

**Issue by teshields** [Genivia/RE-flex#123]
The `%init{ ... }` code block cannot be used to initialize injected Lexer class members of type reference, which must be initialized in the constructor member initializer list.

Proposal: add `%option ctorinit="initializer, initializer, ..."` to add injected member initializers to the constructor's member initializer list, mirroring the existing option `%option ctorarg="argument, argument, ..."` for adding argument declarations to the constructor.

Example:

%class{
int& refint;
bool& refbool;
}
%option ctorarg="int& ri, bool& rb"
%option ctorinit="refint(ri), refbool(rb)"

**Comment by genivia-inc** [comment]
Implemented this feature for the next release cycle.

**Comment by genivia-inc** [comment]
Update 3.2.0 is released.

**Comment by teshields** [comment]
Thanks!
