### ISSUE TITLE
Question: Matcher.matches() does not return group capture index.

### ISSUE THREAD

**Issue by jakob-stark** [Genivia/RE-flex#128]
The [manual states](https://www.genivia.com/doc/reflex/html/#regex-methods-matches):

> The `matches()` method returns a nonzero "accept" value (the `size_t accept()` group capture index value or the value 1 if no groups are used) if the given input from begin to the end matches the specified pattern.

Almost the same is said for the `scan()` method. Now consider the following program

    #include <iostream>
    #include <reflex/matcher.h>

    int main(int argc, char * argv[]) {
        auto pattern = reflex::Pattern("(cat)|(dog)");

        std::cout << reflex::Matcher(pattern, "cat").matches() << std::endl;
        std::cout << reflex::Matcher(pattern, "cat").scan()    << std::endl;

        std::cout << reflex::Matcher(pattern, "dog").matches() << std::endl;
        std::cout << reflex::Matcher(pattern, "dog").scan()    << std::endl;
    }

It prints out

    1
    1
    1
    2

So the `scan()` method actually returns the group capture index value as stated in the manual, but the `matches()` method does not. Is this behaviour intended?

**Comment by genivia-inc** [comment]
I believe this behavior may have changed sometime, because `matches()` was just intended to report a match yes/no. The doc isn't updated. But I agree it is nicer to have the group capture index. Will update the repo with the change to return capture index.

Note that you can also get the capture index afterwards with `Matcher::accept()`.

**Comment by jakob-stark** [comment]
Thanks for the answer and also for the awesome project. I guess I'm just fine to use `Matcher::accept()` but would also appreciate a future change. After all the return value still could be used as a boolean value if it returned the group capture index.

**Comment by genivia-inc** [comment]
Fixed in v3.2.2.
