### ISSUE TITLE
deprecation in C++17 of iterator<std::input_iterator_tag, reflex::AbstractMatcher>

### ISSUE THREAD

**Issue by jlgiavitto** [Genivia/RE-flex#130]
Hello and thanks for the development of RE-flex. 

I use re-flex 3.2.2 on OSX (brew installation) to produce a compelx parser. Recently I have switched to C++17 and I have compilation warnings on the code generated by RE-flex (using the Apple clang compiler) : 

           'iterator<std::input_iterator_tag, reflex::AbstractMatcher>' is deprecated  (located at include/reflex/absmatcher.h:259:14)

and 

          'iterator<std::input_iterator_tag, const reflex::AbstractMatcher>' is deprecated  (located at include/reflex/absmatcher.h:159:32)
    
My understanding is that the helper template std::iterator used to define the iterator traits of an iterator is deprecated in C++17 and must be updated by specifying explicitly some type parameter (cf. https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated).

Even if these two warnings are not a burden for now, it would be great to make the generated code compatible with C++17 and C++20.

**Comment by genivia-inc** [comment]
Thanks for the feedback. Will take a look and update the absmatcher.cpp file accordingly.

**Comment by genivia-inc** [comment]
Should be fixed in the v3.2.3 update available now.
