### ISSUE TITLE
FYI: A couple of weird bugs in flex-compatibility mode

### ISSUE THREAD

**Issue by teshields** [Genivia/RE-flex#137]
I'm running portability tests for an upcoming release of Ox (https://sourceforge.net/projects/ox-attribute-grammar-compiler/), and I've run into a couple of extremely weird bugs adding reflex as an option for several scanners using the '--yy' option for flex-compatibility mode. I'm using release 3.2.7.

1. Using the reflex.a (or reflexmin.a) library from the distribution on the Homebrew site under macOS Monterey 12.4 (ARM M1 chip), reflex-generated flex-compatible scanners compiled with the GNU g++-11 v11.3.0_2 (or g++-12 v12.1.0_1) compiler (also from the Homebrew site) fail to link, due to a mismatch in symbol mangling, as far as I can determine. I've never encountered this type of failure before. As a (temporary) workaround, I'm using a separate version of the reflex libraries compiled with the Homebrew GNU g++-11 compiler for testing in these cases.
2. These flex-compatibility test cases, when configured to use the Boehm-Demers-Weiser garbage collector (BDWGC), again using the GNU g++-11 compiler, segfault in the destructor of the FlexLexer class. If I compile the reflex libraries OMITTING the default '-O2' option using the GNU g++-11 compiler, all test cases work just fine, so this is the version I'm using as the workaround.

To slip the BDWGC library underneath everything, preprocessor macros replace calls to the functions 'free', 'malloc', 'realloc' and 'posix_memalign' in the reflex library with calls to the corresponding BDWGC functions 'GC_free', 'GC_malloc', 'GC_realloc' and 'GC_posix_memalign'.

In an attempt to debug 2 above, I linked with a version of the BDWGC library configured with assertions enabled.

Under lldb, for the segfault case (reflex libraries compiled with '-O2'), 'GC_posix_memalign' is never called, and I get an assertion failure in the BDWGC 'GC_free' function, saying that the object 'AbstractMatcher::buf_' being freed (absmatcher.h, line 335) wasn't allocated by a BDWGC allocation function.  For the 'works just fine' case, 'GC_posix_memalign' is called.

If I can figure out how to modify the code in absmatcher.h to sidestep the GNU g++-11 optimizer bug, I'll let you know.  A simple change to assigning the result of the call to 'posix_memalign' to a local 'volatile int' doesn't make a difference.

**Comment by genivia-inc** [comment]
By the way, to bypass the realloc calls, you may want to set the buffer size large for a large window on the input. This should be large enough to hold the longest matching pattern. It does not need to be as large as the input files. The buffer is 64K by default. To change the buffer, use -DBUFSZ=nnn with appropriate nnn (>4096) to compile all source code (BUFSZ is used in absmatcher.h).

**Comment by genivia-inc** [comment]
I have more questions than answers, since there isn't much here to offer any clues. Questions like these:
- does the FlexLexer class instantiation and destruction crash without scanning input?
- does increasing -DBUFSZ=nnn affect this issue?
- does this issue happen with the BDWGC library? Or also without it?
- is the issue affected by the choice of libreflex or libreflexmin? Or building from source without libraries (reflex/lib files)?
- what does valgrind report? Or...
- try clang with `-fsanitize=memory` and/or `-fsanitize=leak` see https://clang.llvm.org/docs/LeakSanitizer.html to check the application for memory and leak issues

**Comment by teshields** [comment]
FYI: my last debugging efforts (later this week):
1. I'll try importing the source for one of my test cases into Xcode to see if it has any better clues to offer.  Importing existing somewhat complicated command line code (wrt compile & link options & libraries) is always a bit of a pain, but it might tell me something.
2. try out the "experimental" release of the BDWGC library v8.2.0
3. valgrind

I'll report back anything interesting.

**Comment by teshields** [comment]
I'm delinquent in reporting back on my debugging status with respect to these 2 'weird bugs'.

The 'weird bug 1' remains a mystery: The macOS Apple & (Homebrew) LLVM C++ compilers just do not generate (mangled) name references in some cases that are compatible with those generated by macOS (Homebrew) GNU C++ compilers for the RE/flex library. I don't see the same problem with Linux LLVM and GNU C++ compilers and the RE/flex library installed from the Ubuntu repository.

On the other hand, 'weird bug 2' is a self-inflicted wound: My original approach to sliding the BDWGC garbage collector underneath Ox and its test cases worked with Flex, since there is not a Flex-specific library to be linked into the executables. However, I didn't originally notice that the RE/flex library member 'matcher.o' contains external references to both C memory allocation functions and C++ new/delete operators, so in particular, object 'AbstractMatcher::buf_' is being free'd by the BDWGC 'GC_free' function but allocated by the C 'posix_memalign' function. I cannot explicitly state why the segfault only occurs with optimized code, but I'm not exactly surprised, as I've seen analogous segfault situations in the past. I've replace my pre-processor approach with a replacement library for the C allocation functions that are just shells around calls to the corresponding BDWGC functions.

**Comment by genivia-inc** [comment]
Can we close this?

**Comment by teshields** [comment]
SureSent from Tom’s iDeviceOn Mar 25, 2023, at 3:50 PM, Dr. Robert van Engelen ***@***.***> wrote:﻿
Can we close this?
