### ISSUE TITLE
The 'WITH_REALLOC' macro in absmatcher.h should be a boolean value rather than just a defined value

### ISSUE THREAD

**Issue by teshields** [Genivia/RE-flex#138]
If I want to use 'new[]' and 'delete[]' for 'AbstractMatcher::buf_' instead of 'std::free', 'posix_memalign' and 'std::realloc', I have to edit out 'absmatcher.h' line 41 `#define WITH_REALLOC`.  It would be a preferable to use `#if WITH_REALLOC` wherever `#if defined(WITH_REALLOC)` is currently used, and replace line 41 with the following, allowing a user to compile with '-DWITH_REALLOC=0'

```
#ifndef WITH_REALLOC
#define WITH_REALLOC 1
#endif
```

**Comment by genivia-inc** [comment]
Good point. I left this choice in the code for myself. Glad you find it useful too. So I'll update as suggested in the upcoming release. I'll change the other `WITH_` defines accordingly.
