### ISSUE TITLE
Duplicate build rules on Windows

### ISSUE THREAD

**Issue by tlemo** [Genivia/RE-flex#141]
On Windows, the CMake script yields duplicate rules for `reflex.lib`:
`ninja: error: build.ninja:2470: multiple rules generate third_party/reflex/repo/reflex.lib [-w dupbuild=err]`

The problem is that on Windows, building shared libraries (DLLs) normally produce an import library along with the the .dll (`reflex.lib` + `reflex.dll`). This is a problem if the static library is also named `reflex.lib`

It seems it's easy to avoid this issue by using distinct names for the libs & exe. Ie. instead of 

```
set_target_properties(ReflexLibStatic ReflexLib Reflex
  PROPERTIES OUTPUT_NAME reflex
)
```

use:

```
set_target_properties(ReflexLibStatic PROPERTIES OUTPUT_NAME reflex_static_lib)
set_target_properties(ReflexLib PROPERTIES OUTPUT_NAME reflex_shared_lib)
set_target_properties(Reflex PROPERTIES OUTPUT_NAME reflex)
```

Alternatively (perhaps simpler and cleaner) is to just use the target names matching the intended output names.

**Comment by genivia-inc** [comment]
Thanks for contributing. Always nice to see additions and fixes.

But I do not see what cmake files this would apply to? Can you help me out here?

**Comment by tlemo** [comment]
I just created a small PR (#145) for this. Thanks.

**Comment by gahr** [comment]
On  the other hand, it is very inconvenient not to have libreflex.a and libreflex.so on != Windows. Can we at least IF(WIN32) it?

**Comment by tlemo** [comment]
> On the other hand, it is very inconvenient not to have libreflex.a and libreflex.so on != Windows. Can we at least IF(WIN32) it?

Hi @gahr, can you please elaborate? What makes the new names "very inconvenient" on non-Windows platforms?

**Comment by gahr** [comment]
Sorry for commenting in both places, see my reply in #145
