### ISSUE TITLE
-lboost_regex-mt typically not built on Linux

### ISSUE THREAD

**Issue by bkmgit** [Genivia/RE-flex#143]
Use just -lboost_regex in the Examples and Tests Make files

**Comment by genivia-inc** [comment]
I see that newer Boos versions are mt safe now. So that's good to know.

**Comment by bkmgit** [comment]
Solved in https://github.com/Genivia/RE-flex/pull/144

**Comment by genivia-inc** [comment]
OK. So I installed Boost again to see if libboost-regex-mt is included. It is. So why change it?

**Comment by bkmgit** [comment]
This may depend on what operating system is used. A number do not package -mt versions.
