### ISSUE TITLE
The Automake 'ylwrap' script fails using RE/flex compiled under Cygwin

### ISSUE THREAD

**Issue by teshields** [Genivia/RE-flex#147]
The `ylwrap` script, used for Lex source in an Automake-generated Makefile, converts the lexer specification file name into a Unix-style absolute path name before running the lexer generator.

The `reflex` command line tool compiled under Cygwin treats a `/` character on the command line as the start of an option, so I was getting a usage error from `reflex` with no specific problem identified from the build rule. Since this treatment of the `/` character is not mentioned in the User Guide, it took me a while to figure it out what was going on.

In order to make progress, I edited the `reflex.cpp` file to remove the following lines:
```
#ifdef OS_WIN
     || *arg == '/'
#endif
```
Please add a prominent note in the User Guide "The reflex command line tool" section, and maybe also in "Tips, tricks, and gotchas" section about interpreting `/` as the start of a command line option in Windows environments.

I will work out a change to the `ylwrap` script to convert Unix-style absolute paths on the command line to Windows-format in Cygwin, Msys2, and MinGW/Windows environments, and submit it as a change to the FSF.

**Comment by genivia-inc** [comment]
Good point. Perhaps removing the `/` option form is not a bad idea actually, since it's a Unixy-tool. Do you see any downsides to removing `/` as an option?

**Comment by genivia-inc** [comment]
Alternatively, we can check for Cygwin/MingW. This is perhaps better:
~~~
#if defined(OS_WIN) && !defined(__CYGWIN__) && !defined(__MINGW32__) && !defined(__MINGW64__)
     || *arg == '/'
#endif
~~~

**Comment by genivia-inc** [comment]
I will go ahead and make that change in the reflex 3.2.11 update, which I plan release today. This release has a new Lua-to-lisp transpiler example to demonstrate RE/flex with Bison complete symbols and locations.

**Comment by teshields** [comment]
Works for me
