### ISSUE TITLE
CMake moved?

### ISSUE THREAD

**Issue by gahr** [Genivia/RE-flex#148]
CMakeLists.txt was moved into cmake/CMakeLists.cmake. This makes it inconvenient to build the project (cmake looks for CMakeLists.txt). What's the rationale?

**Comment by genivia-inc** [comment]
Because the `cmake` directory has all the Cmake-related stuff, like it did before? Makes sense to me. I did ask you if it was OK to move it there and didn't hear back.

**Comment by genivia-inc** [comment]
Sure, let's move it to the root dir.

I simply never use CMake any longer as it left a bad impression after trying to work with it a couple of times years ago. Granted, those projects were far more demanding than RE/flex with respect to low-level library linkage. No-one was even able to come up with a working CMake back then.

**Comment by genivia-inc** [comment]
Moved in the master branch.

**Comment by gahr** [comment]
> I did ask you if it was OK to move it there and didn't hear back.

Me? Anyway, thanks for moving back!
