### ISSUE TITLE
CMake custom target

### ISSUE THREAD

**Issue by hinell** [Genivia/RE-flex#153]
We need a [custom_command] & [custom_target] that can be used inside CMake projects, similar to one declared by the [FindFLEX] module provided by CMake:

```CMake
FLEX_TARGET(
            Name <FlexInput> <FlexOutput>
            [COMPILE_FLAGS <string>]
            [DEFINES_FILE <string>]
            ... etc
            )
```
[FindFLEX]: https://cmake.org/cmake/help/latest/module/FindFLEX.html
[custom_command]: https://cmake.org/cmake/help/latest/command/add_custom_command.html
[custom_target]: https://cmake.org/cmake/help/latest/command/add_custom_target.html

**Comment by genivia-inc** [comment]
Perhaps create a PR? I'm not sure I want to touch this CMake-specific requirement.
