### ISSUE TITLE
In example yaml.l: wrong arg to parse_seq()

### ISSUE THREAD

**Issue by geert56** [Genivia/RE-flex#159]
In `parse_map` on line 650 `parse_seq(val)` must in all likelihood be `parse_seq(key)` in my opinion.

**Comment by genivia-inc** [comment]
Thanks for the feedback. You're correct.

**Comment by geert56** [comment]
I found some more deficiencies in yaml.l. I decided to start from scratch instead of trying to reverse engineer the original code. YAML is surprisingly complex and hard to lex/parse.
I assume this issue may be closed.

**Comment by genivia-inc** [comment]
The problem is a regression issue in reflex itself. The original reflex 1.5.8 version works as expected! So my testing back then covered many practical cases.

I will look into the regression issue. Something internally isn't working as it should be.

**Comment by genivia-inc** [comment]
Correction. The yaml.l problem is not a regression issue. I was looking into another issue and ran some tests. Looking at the test results of previous versions to compare, I interpreted the yaml test results incorrectly.
