### ISSUE TITLE
Drop RTTI requirement

### ISSUE THREAD

**Issue by sgothel** [Genivia/RE-flex#161]
1st of all thank you for your work.

I tested your project within this little test project [calc_infix2rpn](https://github.com/sgothel/calc_infix2rpn).

After compiling your library w/ `-fPIC` I also needed to move from `dynamic_cast` to `static_cast` to allow not using RTTI, i.e. `-fno-rtti`.
[no_rtti.patch.txt](https://github.com/Genivia/RE-flex/files/10297661/no_rtti.patch.txt)

Not sure how to inject this patch using an option and w/o an ugly macro, so I just hard-patched it for now.

+++

I added the cmake integration file `FindREflex.cmake` in above project `calc_infix2rpn`, as it was [posted here by KFAFSP](https://gist.githubusercontent.com/KFAFSP/8ca884738f4558df29a3b32e47730306/raw/fe0d8a6366cc85f48a05d33328a8d4f3d864a776/FindREflex.cmake), it is working well.

**Comment by sgothel** [comment]
@KFAFSP tagging you for FindREflex.cmake, see above

**Comment by genivia-inc** [comment]
Thank you for the feedback. This change is fine and will be part of the next update.
