### ISSUE TITLE
Inconsities in generated file names and documentation.

### ISSUE THREAD

**Issue by SouravKB** [Genivia/RE-flex#164]
Documented:
> −−header-file[=FILE]
This option generates a C++ header file `FILE.h` that declares the lexer class ...

Actual:
*This option generates a C++ header file `FILE` rather than `FILE.h`.*

---

Documented:
> −−tables-file[=FILE]
This option generates a C++ file `FILE.cpp` with the finite state machine in source code form ...

Actual:
*This option generates a C++ file `FILE` if `FILE` ends with `.cpp`, otherwise generates `FILE.cpp`.*

---

Documented:
> −−regexp-file[=FILE]
This option generates a text file `FILE.txt` that contains the scanner's regular expression patterns ...

Actual:
*This option generates a text file `FILE` if `FILE` ends with `.txt`, otherwise generates `FILE.txt`.*

---

Documented:
> −−graphs-file[=FILE]
This option generates a Graphviz file `FILE.gv` ...

Actual:
*This option generates a Graphviz file `FILE` if `FILE` ends with `.gv`, otherwise generates `FILE.gv`.*

**Comment by SouravKB** [comment]
The constants - `REFLEX_OPTION_tables_file`, `REFLEX_OPTION_regexp_file`, `REFLEX_OPTION_graphs_file` - in generated outfile always has the value of `FILE`, whereas the corresponding constants in generated header-file has the value of actual generated file names (`FILE[.cpp]`, `FILE[.txt]`, `FILE[.gv]`).

**Comment by SouravKB** [comment]
My personal suggestion would be to always use `FILE` as generated file name. Though it may not be possible to change that now as it may break existing projects.

**Comment by genivia-inc** [comment]
> Documented:
> 
> > −−tables-file[=FILE]
> > This option generates a C++ file `FILE.cpp` with the finite state machine in source code form ...
> 
> Actual: _This option generates a C++ file `FILE` if `FILE` ends with `.cpp`, otherwise generates `FILE.cpp`._

When the extension is the default like .cpp, then here is no need to add an extension, which would produce files like `FILE.cpp.cpp`. So this is correct. Same for `graphs-file`  and `regexp-file`. This is logical and doesn't need further explanation.

The `header-file` should add a `.h` if not provided, but that appears not to be the case so I'll check the logic to correct this.

**Comment by genivia-inc** [comment]
BTW. The fact that `header-file` doesn't add the extension is because Flex doesn't and RE/flex is largely backward compatible to Flex.

**Comment by SouravKB** [comment]
In that convention, `outfile` should also add `.cpp` extension if not present in `FILE`.

You can add `.hpp` extension to `header-file` and `.cpp` extension to `outfile` only when `%o flex` is not specified. Much like how other backward comapatibilty featues work.

**Comment by SouravKB** [comment]
> The constants - REFLEX_OPTION_tables_file, REFLEX_OPTION_regexp_file, REFLEX_OPTION_graphs_file - in generated outfile always has the value of FILE, whereas the corresponding constants in generated header-file has the value of actual generated file names (FILE[.cpp], FILE[.txt], FILE[.gv]).

You haven't said anything about this!
