### ISSUE TITLE
Error while using Unicode characters adjacent to braces.

### ISSUE THREAD

**Issue by SouravKB** [Genivia/RE-flex#166]
When I write an unicode character directly adjacent to opening brace in lex file, it fails, saying '{' mismatched.

Minimal reproducible example:
```
%o main unicode
x .
%%
§{x} echo();
%%
```
Compilation output:
```
test.ll:4: error: malformed regular expression or unsupported syntax
error at position 4
┬º{x}
   \___mismatched { }

```

But the regex pattern itself isn't malformed. `§+{x}`, `§""{x}`, `[§]{x}` compiles perfectly fine. I have tried putting various non-ascii unicode characters. All gives same error.

**Comment by genivia-inc** [comment]
This works for me with `freespace`, which permits spacing in regex patterns (but actions _must_ be placed in curly braces):
~~~
%o main unicode freespace
x x
%%
§ {x} { echo(); }
%%
~~~
I think the problem may have something to do with the macro expansion logic with unicode. Will check it further.
