### ISSUE TITLE
\s matches \n ?

### ISSUE THREAD

**Issue by tlemo** [Genivia/RE-flex#171]
Contrary to the documentation, it seems that `\s` is matching `\n` (at least when used in a lexer specification), is this intentional?

**Comment by genivia-inc** [comment]
In a lexer specification `\s` matches `\n`. This the usual regex interpretation of `\s`.

There is a typo in the table in section "Character categories" (will fix that), but the other table in section "Unicode mode" is correct.

[Ugrep](https://github.com/Genivia/ugrep) makes an exception to make it behave like grep. The RE/flex regex converter has a flag `reflex::convert_flag::notnewline` to override `\s` to ignore `\n`, which is used by ugrep.

**Comment by genivia-inc** [comment]
The [online manual](https://www.genivia.com/doc/reflex/html/index.html) is updated.
