### ISSUE TITLE
unicode character classes not recognized

### ISSUE THREAD

**Issue by GorillaSapiens** [Genivia/RE-flex#172]
../reflex/RE-flex/src/reflex -yy --unicode --header-file=lex.yy.hpp polybasic.l
polybasic.l:77: error: malformed regular expression or unsupported syntax
error at position 13
[\p{Letter}\p{MiscellaneousSymbols}\p{Emoticons}\p{SupplementalSymbolsandPictog
                 \___invalid character class

similar problems with \p{Emoticons} \p{SupplementalSymbolsandPictographs} etc...
i specified %option unicode as well as --unicode on the command line.
what am i doing wrong?

**Comment by GorillaSapiens** [comment]
looks like the forum mangled the error.  \p{MiscellaneousSymbols} is what's causing the problem here

**Comment by GorillaSapiens** [comment]
aha, seems you need \p{IsMiscellaneousSymbols} to make it work.  the documentation should probably be updated to make this more clear.  it wasn't very intuitive for me as an experienced programmer but first time user of this software.

**Comment by genivia-inc** [comment]
Ah, I think you're right about the unnecessary confusion. The block name is `isBlockName` but the table does not include the `is` part. Will fix that.

**Comment by genivia-inc** [comment]
Online manual is updated.
