### ISSUE TITLE
reflex::Matcher needs a virtual destructor

### ISSUE THREAD

**Issue by tlemo** [Genivia/RE-flex#174]
I just noticed that the `reflex::Matcher` class has virtual methods, but no virtual destructor. This is problematic when instances of classes derived from Matcher are deleted though a `Matcher*` pointer (specifically, w/o a virtual destructor this is undefined behavior)

The fix is trivial:

```
virtual ~Matcher() = default;
```

**Comment by tlemo** [comment]
Nevermind - the base classes, starting `reflex::AbstractMatcher` already have virtual destructors. Sorry for the false alarm.

**Comment by genivia-inc** [comment]
Thanks for checking. Having more eyes on the code always helps!
