### ISSUE TITLE
unicode character classes documentation problem

### ISSUE THREAD

**Issue by GorillaSapiens** [Genivia/RE-flex#175]
i'd have re-opened #172 but i don't know how. sorry

if you go to https://www.genivia.com/doc/reflex/html/#reflex-pattern-class and scroll down to "IsUnifiedCanadianAboriginalSyllabicsExtended-A" you'll see the html table seems to go off the rails and become garbled / unintelligible.

this happens in chrome, on both Windows and Linux.

also, when i do a checkout, i do *not* see these changes in my local copy.  i'm assuming you're holding them in a branch somewhere?

**Comment by Robert-van-Engelen** [comment]
The doc changes are only made online at this time until the next release cycle.

**Comment by genivia-inc** [comment]
Fixed the online docs. Thanks for reporting!
