### ISSUE TITLE
issue to compile multiple buffer input buffers

### ISSUE THREAD

**Issue by ClaudioDaffra** [Genivia/RE-flex#18]
I am trying to include multiple buffer with RE-flex.
I'm referring to this example : [http://dinosaur.compilertools.net/flex/flex_12.html#SEC12](url) Flex
because i have not found example in REflex directory, however something has gone wrong, 

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xlocale(319): warning C4530: utilizzato gestore eccezioni C++, ma la semantica di rimozione non è abilitata. Specificare /EHsc
    parser.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include\xlocale(319): warning C4530: utilizzato gestore eccezioni C++, ma la semantica di rimozione non è abilitata. Specificare /EHsc
    main.parser(67): error C2355: 'this': ...
    main.parser(69): error C2355: 'this': ...
    main.parser(71): error C2355: 'this': ...
    main.parser(84): error C2355: 'this': ...
    main.parser(85): error C2355: 'this': ...
    Generazione del codice in corso...

above the offending error 

flex

    <<EOF>>         { return FINE; }
    "include"       { return INCLUDE; }
    [[:digit:]]+    { yylval.num = atoi(yytext);   return NUMBER; }
    [[:alnum:]]+    { yylval.str = strdup(yytext); return STRING; }
    "="|";"         { return yytext[0]; }
    .|\n            {}

bison

    INCLUDE
    {
        printf  ("#include#\n");        
        if ( include_stack_ptr >= MAX_INCLUDE_DEPTH )
        {
            fprintf( stderr, "Includes nested too deeply" );
            exit( 1 );
        }
        include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;

        yyin = fopen( "main2.test", "r" );

        yy_switch_to_buffer( yy_create_buffer( yyin, YY_BUF_SIZE ) );
    }
    |
    FINE 
    { 
        printf  ("#eof#\n");
        if ( --include_stack_ptr < 0 )
            {
            yyterminate();
            }

        else
            {
            yy_delete_buffer( YY_CURRENT_BUFFER );
            yy_switch_to_buffer(include_stack[include_stack_ptr] );
            }
    }
i have done a workaround , but also in this case something has gone wrong : 

    INCLUDE
    {
        printf  ("#include#\n");        
        buffer.push (  static_cast<yyscanner_t*>(scanner)->in() ) ;
        FILE* fi2 = fopen ( "main2.test","r" ) ;
        static_cast<yyscanner_t*>(scanner)->flush() ;    
        static_cast<yyscanner_t*>(scanner)->in(fi2) 

    }
    |
    EOF    
    {
        printf  ("#eof#\n"); 
        fclose ( buffer.top() ) ;
        buffer.pop();
        static_cast<yyscanner_t*>(scanner)->flush() ;    
        static_cast<yyscanner_t*>(scanner)->in(buffer.top()) ;   
   
    }

I ask you a solution or put a full working source code in directory example.

thank you for time
Claudio

**Comment by genivia-inc** [comment]
This should in principle work (the second attempt). Your first attempt will cause problems with `yyterminate()` though I am thinking there is a way to get that to work properly. I had an example of this somewhere and will take a look to post it.

**Comment by ClaudioDaffra** [comment]
I have found this solution, in principle it works.


RE-flex :

    <<EOF>>         { return FINE; }
    "include"       { return INCLUDE; }

bison :

        %top{
        std::stack<yyscanner_t*> buffer ;
        }
        
...

 ```
     |
        INCLUDE    
        {
            printf  ("#include#\n");
            
            buffer.push ( static_cast<yyscanner_t*>(scanner) ) ;
            
            static_cast<yyscanner_t*>(scanner)->matcher().flush();
            
            yyscanner_t scannerInclude;
            
            FILE* fi=fopen( "main2.test", "r" );
            
            scannerInclude.in(fi);

            buffer.push ( &scannerInclude ) ; 
            
            yyparse ( &scannerInclude ) ;
            
        }
    |
        FINE 
        { 
            printf  ("#eof#\n");

            static_cast<yyscanner_t*>(buffer.top())->matcher().flush();
                    
            buffer.pop() ;
            
            yyparse ( buffer.top() ) ;

        }

    ;
    
```
is there a better way to do this ?

**Comment by ClaudioDaffra** [comment]
I have fixed seg fault in example 10, i send you pull request :  

```
claudio@ubuntu:~/RE-flex.save/examples$ bison -d -y example10.y -o parser.cpp
claudio@ubuntu:~/RE-flex.save/examples$ reflex --flex --bison-locations --bison-bridge --header-file=lexer.hpp example10.l -o lexer.cpp
claudio@ubuntu:~/RE-flex.save/examples$ g++ lexer.cpp parser.cpp -o example10 -I ../include/ ../lib/libreflex.a
claudio@ubuntu:~/RE-flex.save/examples$ ./example10 

 lexer  at 3,2 
 lexer  at 5,2 
 lexer  at 9,2 (setf abc 123)

 lexer  at 11,2 
 lexer  at 3,2 
 lexer  at 5,2 
 lexer  at 9,2 (setf xyz 789)

 lexer  at 11,2 
 lexer  at 0,3 

 lexer  at 3,4 
 lexer  at 5,4 
 lexer  at 9,4 (setf def 456)

 lexer  at 11,4 FILE : example10b.test error : error parser at 3,1

 lexer  at 5,5 
 lexer  at 0,6 
claudio@ubuntu:~/RE-flex.save/examples$ 
```
