### ISSUE TITLE
uncaught exception: %option ctorinit with string constant line continuation

### ISSUE THREAD

**Issue by teshields** [Genivia/RE-flex#183]
I tried using a string constant with a line continuation in the **ctorinit** option and got an uncaught exception:

source:
```
// L-file lexer constructor specification
%option ctorarg="Lfile_specIO& fR"
%option ctorinit="EOLstate (EOLctx (position (&fR.inName, 0, 0))), \
theFiles (fR)"
```

error:
```
libc++abi: terminating due to uncaught exception of type std::out_of_range: basic_string
/bin/sh: line 1: 80210 Abort trap: 6           reflex --debug --full --header-file=reflex/agc-Lfile-internal.hh -o reflex/agc-Lfile-lexer.cc reflex/agc-Lfile-lexer.ll
```

This would be a nice extension for cases where the initialization is an extremely long string constant.

**Comment by genivia-inc** [comment]
Hm. Parsing option values by the code generation tool seems to go haywire somewhere. Should be easy to fix.

I agree that line continuations are useful and should be obeyed.

Thanks for sharing to make RE/flex better!

**Comment by genivia-inc** [comment]
I fixed it in the development version. I can't create an update right now and that has to wait until later, after a week.

**Comment by genivia-inc** [comment]
I will upload the fixed source code shortly, but can't create an official release yet.
