### ISSUE TITLE
how to build lexer supports uncode?

### ISSUE THREAD

**Issue by haihuayang** [Genivia/RE-flex#184]
Hello,

I made following change to build wc with unicode support, but when I tried some utf8 input, wc does not report correct number of characters, instead it just report the number of bytes, same as without the option '--unicode'. Is there anything I missed?

Thanks,

```
$ git diff
diff --git a/examples/Make b/examples/Make
index 4080e27c..474e1049 100644
--- a/examples/Make
+++ b/examples/Make
@@ -326,7 +326,7 @@ calc:               calc.l calc.y
                ./calc < calc.test

 wc:            wc.l
-               $(REFLEX) $(REFLAGS) --flex wc.l
+               $(REFLEX) $(REFLAGS) --flex --unicode wc.l
                $(CXX) $(CXXFLAGS) -o $@ lex.yy.cpp $(LIBREFLEX)

 wcu:           wcu.l

``` 

```
$ echo 好 | ./wc
       1       1       4
```

**Comment by genivia-inc** [comment]
Please read the documentation on how to use RE/flex if you want to make changes.

The `yyleng` value is always backward compatible with Flex to count bytes, not characters. Same as the `size()` method. Use `wsize()` method to count (wide) characters, i.e. Unicode characters.
