### ISSUE TITLE
using --stdout and --full option does not output reflex_code_INITIAL

### ISSUE THREAD

**Issue by haihuayang** [Genivia/RE-flex#185]
Hi,
when I use both --stdout --full option to generate the lexer, reflex does not output reflex_code_INITIAL. it looks like in function Pattern::assemble opt_f is empty when using --stdout option.
  if (!opt_.f.empty())
  {
    if (opt_.o)
      gencode_dfa(start);
    else
      export_code();
  }

is it by design or a bug?

Thanks,

**Comment by genivia-inc** [comment]
This should be working now with the upcoming update v3.3.6.
