### ISSUE TITLE
Setting up a project that uses a lexer is a bit complicated

### ISSUE THREAD

**Issue by butlerem01** [Genivia/RE-flex#186]
Every time I set up a C++ project that uses this lexer I have to add one or more of the .cpp files in Reflex's lib directory to my project. Not knowing what I should add or what I shouldn't, I just add all the .cpp files to my project. But it seems excessive. Does it really have to be like this? With Flex, I only need to add the main Flex directory as an include directory so FlexLexer.h can be included, but with Reflex it produces all these dependencies for my project.

**Comment by genivia-inc** [comment]
The `lib/libreflex` library has everything. The `lib/libreflexmin` library is minimized with only the essentials. See the reflex/doc/index.html or visit [the manual](https://www.genivia.com/doc/reflex/html/index.html) and read section [Minimized library and cross compiling](https://www.genivia.com/doc/reflex/html/index.html#linking) and [The RE/flex regex library](https://www.genivia.com/doc/reflex/html/index.html#regex).

You can build everything from source too, which may require all C++ files in reflex/lib to be compiled, but there aren't that many IMO:

![image](https://github.com/Genivia/RE-flex/assets/13117347/803d2598-bbca-4343-880f-442a074bb947)
