### ISSUE TITLE
Build tests with CMake

### ISSUE THREAD

**Issue by szhorvat** [Genivia/RE-flex#192]
This is a request to make it possible to build the tests (and examples) with CMake.

Since RE/flex can be built either with CMake or autotools, is there a recommendation on which one to use when packaging this tool? See [this PR](https://github.com/macports/macports-ports/pull/20567) to add RE/flex to MacPorts (comments welcome).

**Comment by genivia-inc** [comment]
Thank you for your comments and suggestions.

I prefer autotools, simply because I've been using those for a long time. CMake is a fine tool too. I have some basic-level experience with it, but it will take me quite a bit of effort to rewrite the configuration and installation. The autoconf script checks for architectural features by running some custom autoconf-generated code to check for SSE2/AVX2/AArch64. This was tricky to write to work with clang and GCC and with various OS. See the configure.ac script to see what I mean. Doing this again for cmake and test it all out with various OS, clang and GCC, is not something that can be done overnight.

**Comment by szhorvat** [comment]
Thanks for the response. All I needed was clarity on which build system to prefer when including RE/flex in a repo like MacPorts and this makes it clear.

Once the PR I referred to is merged, you might consider adding MacPorts installation instructions [to the README, along with the Homebrew ones](https://github.com/Genivia/RE-flex#unixlinux-and-mac-os-x). The command will be `sudo port install re-flex`. But let's wait until the PR is merged.

A question regarding packaging RE/flex: I notice that [Homebrew](https://formulae.brew.sh/formula/re-flex) adds `pcre2` as a dependenc, and [Nix](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/tools/parsing/re-flex/default.nix#L5) adds boost. As far as I can tell, these are unnecessary either for building or using RE/flex. They are optional when linking the code produced by RE/flex. Can you confirm that my understanding is correct?

**Comment by genivia-inc** [comment]
> A question regarding packaging RE/flex: I notice that [Homebrew](https://formulae.brew.sh/formula/re-flex) adds `pcre2` as a dependency, and [Nix](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/tools/parsing/re-flex/default.nix#L5) adds `boost`. As far as I can tell, these are unnecessary either for building or using RE/flex. They are optional when linking the code produced by RE/flex. Can you confirm that my understanding is correct?

There are no dependencies. You're right about linking the generated code optionally with PCRE2 or Boost. So, by default, there are no dependencies at all. RE/flex has a POSIX-compliant regex pattern engine that is compatible with Flex which means nothing needs to be added by default. Only if the user wants to use PCRE2 or Boost then he/she can do so at any time later. RE/flex also includes a "flexible" regex engine API abstraction layer which wraps PCRE2 and Boost, but that is optional too.

**Comment by genivia-inc** [comment]
I am working today on an update v3.4.1 with one minor improvement related to support for word boundaries (`\b` `\B` `\<` `\<`). This RE/flex update is already used by [ugrep](https://github.com/Genivia/ugrep). I will add MacPorts installation instructions to RE/flex, perhaps though it might be a bit too early, but then I don't need to release RE/flex later again.

**Comment by genivia-inc** [comment]
Thank you for your help!

**Comment by szhorvat** [comment]
FYI the MacPorts PR is finally merged, RE/flex is now available in MacPorts.

I think we can close this issue now, since you answered my question.
