### ISSUE TITLE
Subscripts not working correctly?

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#194]
rational        [0-9]*([⅒⅑⅛⅐⅙⅕¼⅓½⅖⅔⅜⅗¾⅘⅝⅚⅞]|([⁰¹²³⁴⁵⁶⁷⁸⁹]+\/[₀₁₂₃₄₅₆₇₈₉]+))

This tokenizes ³³/₄₅₆
to ³³/₄

[EDIT] Works when I replace \/ with [/] so likely nothing to do with unicode but with / operator?

**Comment by genivia-inc** [comment]
The `/` operator in Lex and Flex and RE/flex is called "trailing context" and is essentially a lookahead. A pattern matches if the lookahead matches also, but the lookahead is removed from the match.
