### ISSUE TITLE
'#' characters in the lexer pattern

### ISSUE THREAD

**Issue by ryanbinns** [Genivia/RE-flex#2]
Attempting to match a literal '#' in the lexer pattern when the freespace option is enabled doesn't trigger any error or warning, but the re-flex matcher interprets it as the beginning of a comment in the regular expression. It therefore discards the remainder of the pattern and displays an error about a mismatched parenthesis at the end of the pattern.

The workaround is to match the '#' as '\x1d' or similar, but this behaviour is not mentioned anywhere in the documentation. If the freespace option is not enabled, it works properly.

Example 4 under "POSIX versus Perl matching" in the user guide fails to work because of this.

**Comment by genivia-inc** [comment]
Thanks for the feedback.

I agree that the # should be matched, even though regex matchers often will ignore a line starting with # as comments in free space mode.

That’s what the reflex code was designed to do, but there is a glitch. I will update the RE/flex regex converter.

- Robert
