### ISSUE TITLE
Pass parameters with using FLEXFIX

### ISSUE THREAD

**Issue by Albertweiku** [Genivia/RE-flex#201]
How does reflex use the FLEXFIX argument to pass arguments to yylex like flex？

**Comment by genivia-inc** [comment]
Can you point to the Flex documentation that defines this FLEXFIX argument? It's not mentioned in the official Flex documentation.

Arguments passed to `yylex()` depend on options. The argument list can also be extended with whatever parameters you want using `%option params="PARAMS"` see [manual](https://www.genivia.com/doc/reflex/html/index.html#reflex-lexer) and also [`YY_DECL` alternatives](https://www.genivia.com/doc/reflex/html/index.html#YYDECL)

**Comment by Albertweiku** [comment]
I solved the problem of passing parameter values by using %option params="PARAMS", thanks.
