### ISSUE TITLE
MSVC error 2229

### ISSUE THREAD

**Issue by Albertweiku** [Genivia/RE-flex#202]
Generation method:
- Use re-flex 4.1;
The build option uses --flex --header-file -i

The problem is that the resulting header file contains a large number of structure or bit fields whose members contain an array of size zero, but that is not the last member. This causes errors when compiling with msvc.

https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2229?view=msvc-170

**Comment by genivia-inc** [comment]
OK, but do you have an example lexer input file for us to replicate the problem so we can fix it? That would help. Without a test case we can only guess, since the tool and the output generation has lots of options.

**Comment by Albertweiku** [comment]
![image](https://github.com/Genivia/RE-flex/assets/81621826/64ab1824-c8bb-4b69-8706-635e35a41177)
![image](https://github.com/Genivia/RE-flex/assets/81621826/aa9ae9e7-c410-42e7-8264-2e78015fcd4c)
![image](https://github.com/Genivia/RE-flex/assets/81621826/2426fd74-7086-4878-bc4a-59dd38fd3844)

Even if I use a near-empty lex file to generate the header file, it has an array of declared size 0.This seems to be a disallowed behavior in MSVC.
Is it because there is a problem with my options?

**Comment by genivia-inc** [comment]
That output is generated with option `-p`. These arrays track the performance of every lexer rule. If there are no rules specified, then these arrays are empty.

This never happens with normal lexer specifications that have at least one rule. Lexer specifications that do not have rules are not useful.

Perhaps the reflex tool should just bail out with an error and not generate any code when no rules are specified.
