### ISSUE TITLE
Declaration hides previous local declaration

### ISSUE THREAD

**Issue by dlorre** [Genivia/RE-flex#217]
Hello, I'm trying to compile Re-Flex with Unreal Engine 5.5 and the setup is that all warnings are treated as errors. As such I get plenty of errors like this one:

Reflex\lib\pattern.cpp(1229): error C4456: declaration of 'k' hides previous local declaration

It's easily fixed on my side, however it's error-prone and I need to do it again every time I want to update.

There are a few others warnings but this is the main problem.

**Comment by dlorre** [comment]
The second issue I have is changing:

    for (size_t offset = std::max(HFA::MAX_CHAIN - 1, level) + 1 - HFA::MAX_CHAIN; offset < level; ++offset)

into this:

    for (size_t offset = std::max<size_t>(HFA::MAX_CHAIN - 1, level) + 1 - HFA::MAX_CHAIN; offset < level; ++offset)

**Comment by genivia-inc** [comment]
> Hello, I'm trying to compile Re-Flex with Unreal Engine 5.5 and the setup is that all warnings are treated as errors. As such I get plenty of errors like this one:
> 
> Reflex\lib\pattern.cpp(1229): error C4456: declaration of 'k' hides previous local declaration

An oversight on my end that wasn't caught by clang as I'm mostly using `-Wall -Wextra -Wunused`.

Renaming the early local `k` to `d` removes the warning:
```cpp
      size_t d = 0;
      for (Location i = 0; i < 7 && std::isdigit(c = at(++loc)); ++i)
        d = 10 * d + (c - '0');
      if (d > Position::MAXITER)
        error(regex_error::exceeds_limits, loc);
      Iter n = static_cast<Iter>(d);
```
This change makes sense, although I don't get a warning here, because both `HFA::MAX_CHAIN` and `level` are `size_t`. So it should not be necessary to specialize `std::max()` but won't hurt:
```
for (size_t offset = std::max<size_t>(HFA::MAX_CHAIN - 1, level) + 1 - HFA::MAX_CHAIN; offset < level; ++offset)
```

**Comment by genivia-inc** [comment]
I've committed a minor update to the source code repo with a few changes to appease all `-Wunused` warnings. This update will find its way into the upcoming release 5.1 (not ETA yet).

**Comment by genivia-inc** [comment]
I meant to write "appease all `-Wshadow` warnings" to close this issue.
