### ISSUE TITLE
Consider adding benchmark: hyperscan

### ISSUE THREAD

**Issue by steakknife** [Genivia/RE-flex#22]
On page https://www.genivia.com/reflex.html, consider benchmarking against [hyperscan](https://www.hyperscan.io/). [Technical details overview here](https://www.hyperscan.io/2015/10/20/match-regular-expressions/).

**Comment by genivia-inc** [comment]
Hyperscan is too buggy to be useful for a comparison. I tried several things to get it working, but I gave up once I figured that common patterns do not work such as `[A-Za-z]+`. Patterns such as this are quite common in lexers.

Here is a simple example showing that Hyperscan fails:

~~~
cd /usr/local/Cellar/hyperscan/5.1.0/share/doc/hyperscan/examples
cc -I/usr/local/Cellar/hyperscan/5.1.0/include/hs -L/usr/local/Cellar/hyperscan/5.1.0/lib -lhs simplegrep.c
./a.out '[A-Za-z]+' simplegrep.c
Scanning 8033 bytes with Hyperscan
Match for pattern "[A-Za-z]+" at offset 7
Match for pattern "[A-Za-z]+" at offset 8
Match for pattern "[A-Za-z]+" at offset 9
Match for pattern "[A-Za-z]+" at offset 10
Match for pattern "[A-Za-z]+" at offset 11
Match for pattern "[A-Za-z]+" at offset 12
Match for pattern "[A-Za-z]+" at offset 13
Match for pattern "[A-Za-z]+" at offset 14
Match for pattern "[A-Za-z]+" at offset 15
Match for pattern "[A-Za-z]+" at offset 18
~~~
But the file simplegrep.c starts with:
~~~
/*
 * Copyright (c) 2015, Intel Corporation
 *
~~~
Hyperscan's `hs_scan` is used in simplegrep.c works for search words like `Hyperscan` but does not work for `[A-Za-z]+` and other patterns.

A very simple grep utility indeed when it can't match common regex patterns 🙁 Perhaps useful as a fgrep (fast grep) but useless for lexers.

**Comment by genivia-inc** [comment]
I implemented an scanner test with Hyperscan using `hs_compile_multi` and `hs_scan`, though Hyperscan returns too many matches, returning `abc`, `bc`, and `b` for pattern `[a-z]+` for example.

The results do not look great for Hyperscan compared to reflex and flex:

    Command / Function                                      | Software                 | Time (μs)
    ------------------------------------------------------- | ------------------------ | ---------
    reflex −−fast                                           | RE/flex                  | 13
    flex −+ −−full                                          | Flex                     | 17
    reflex −−full                                           | RE/flex                  | 29
    boost::spirit::lex::lexertl::actor_lexer::iterator_type | Boost.Spirit.Lex         | 40
    hs_compile_multi(), hs_scan()                           | Hyperscan                | 209
    reflex −m=boost-perl                                    | Boost.Regex              | 230
    pcre2_match()                                           | PCRE2 (pre-compiled)     | 318
    reflex −m=boost                                         | Boost.Regex POSIX        | 450
    flex −+                                                 | Flex                     | 3968
    RE2::Consume()                                          | RE2 (pre-compiled)       | 5088
    RE2::Consume()                                          | RE2 POSIX (pre-compiled) | 5420
    std::regex::cregex_iterator()                           | C++11 std::regex         | 14784

Note: *Best times of 10 tests with average time in microseconds over 100 runs
(using clang 9.0.0 with -O2, 2.9 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3).
Hyperscan disqualifies as a potential scanner due to its event handler
requirements.* [Download the tests](https://www.genivia.com/files/perfcomp.zip)
