### ISSUE TITLE
Attempting to add custom matcher generates invalid class name

### ISSUE THREAD

**Issue by tegtmeye** [Genivia/RE-flex#23]
I'm attempting to add a custom matcher (mostly for experimental purposes) and I've come across a couple bugs. I am very impressed with this work so please don't take anything below as criticism.

Under the "Switching input sources" section of the documentation it states:

> Use reflex options −−matcher=NAME and −−pattern=reflex::Pattern to use your new matcher class NAME (or leave out −−pattern for Boost.Regex derived matchers).

First it appears that `--matcher` is an invalid cmd-line option (seems `-m` works) but that is fairly minor.

A bigger issue is that given the option `-m foo` attempts to generate the following in the generated Lexer class:

> typedef reflex::FlexLexer<foo.h> FlexLexer;

Digging into the code, it appears that the following is the cause. I suspect that adding "const-correctness" in these areas would likely have correctly tripped up the compiler.

In `reflex.cpp` under `void Reflex::set_library()` you pull a string out of the options["matcher"] map as non-const (line 610). Later, you call `file_ext()` method (line 247) to set the include file. The `file_ext` claims to return a copy of the given string but actually does not. It modifies the argument which is then used to set `library->matcher = name.c_str();` (line 632) which also the value of `options["include"]` (line 626).

I was going to fix and send you a pull request but there appear to be some bigger implications that I suspect you would like to handle according to your vision for the application. Basically, issuing `--matcher` also automatically adds an include file with the same name but with hyphens converted to underscores. As far as I can tell, this behavior is undocumented and would cause compilation failures that would be hard to track down without looking at the generated Lexer.

Thanks again and let me know if you need additional explanation.

`
$ reflex --version
reflex 1.1.0 x86_64-apple-darwin18.2.0
$ git log -n1
commit 59d0a7e6bb4ba71c7d63e1d5988a3d9e45e13c88 (HEAD -> v1.1.0, tag: v1.1.0, origin/master, origin/HEAD, master)
Author: Robert van Engelen <ravengelen@gmail.com>
Date:   Wed Feb 20 21:57:27 2019 -0500

    released 1.1.0
    
    Code quality updates + LGTM hook.
$ uname -a
Darwin pinion.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
`

**Comment by genivia-inc** [comment]
Thanks for the feedback. 

The `-m` and `--matcher` options work fine with the current choice of matchers provided, as intended. Here is an example based on `wc.l` but using a Boost POSIX matcher:

```
../bin/reflex  --matcher=boost --flex wc.l
c++ -Wall -Wunused -Wextra -Wno-unused-label -O2 -I. -I../include -I /opt/local/include  -I /opt/local/include -o wc_boost lex.yy.cpp ../lib/libreflex.a /opt/local/lib/libboost_regex-mt.dylib
```

However, there is indeed an issue with the custom matcher in the template parameter `typedef reflex::FlexLexer<foo.h> FlexLexer` which is easy to correct with this patch that is part of the upcoming update:

```
void Reflex::set_library()
{
  if (!definitions.empty())
    warning("%option matcher should be specified before the start of regular definitions");
  if (options["matcher"] == "reflex")
  {
    options["matcher"].clear();
  }
  else if (!options["matcher"].empty())
  {
    std::string& name = options["matcher"];
    std::string name_ext = name;
    size_t pos;
    while ((pos = name.find('-')) != std::string::npos)
      name[pos] = '_';
    LibraryMap::iterator i = libraries.find(name);
    if (i != libraries.end())
    {
      library = &i->second;
    }
    else
    {
      library = &libraries[name];
      library->name = name.c_str();
      if (options["include"].empty())
        options["include"] = file_ext(name_ext, "h");
      else
        options["include"] = file_ext(options["include"], "h");
      library->file = options["include"].c_str();
      if (options["pattern"].empty())
        library->pattern = "char *";
      else
        library->pattern = options["pattern"].c_str();
      library->matcher = name.c_str();
      library->signature = "m:";
      warning("using custom matcher ", library->name);
    }
  }
}
```

**Comment by tegtmeye** [comment]
Great! Thanks for the fix.
