### ISSUE TITLE
Handling of bison locations appears to break common uses of this functionality

### ISSUE THREAD

**Issue by tegtmeye** [Genivia/RE-flex#24]
Hello,

Unless I am missing something, RE-flex's automatic handling of bison locations does not appear to work as expected and the automatic features appears to prevent common uses and a users ability to fix it.

Unexpected behavior 1: In my experience, calculated locations reference the beginning of the match -1 and the end of a match. Looking at the generated re-flex code, I see:

``` 
virtual int yylex (semantic_type* yylval, location_type* yylloc,...)
  {
    yylloc->step();
    int ret = yylex(*yylval);
    yylloc->end.line = matcher().lineno();
    yylloc->end.column = matcher().columno();
    return ret;
  }
```

My interpretation is that the above code assigns the begin to previous matched end which is fine, after the call to yylex, it sets the end to the current values of end to the beginning of the match not the end. That is to say, I would have expected it to be:

```
yylloc->end.line = matcher().lineno() + determine_if_match_has_newline(); // or similar
yylloc->end.column = matcher().columno() + size();
```

Unexpected behavior 2: In addition to simply calculating location data, any non-trivial use of a Lexer needs to be able to access location data within rules for decent error reporting. bison includes examples of use that it supports and recommends. For example in section **10.1.7.4 Calc++ Scanner** of the bison documentation where numeric overflows detected in the scanner are handled and thrown back to the parser via: `yy::parser::syntax_error`. It does not appear to be possible to accomplish this in re-flex without inheriting from the generated Lexer and redefining `yylex (semantic_type* yylval, location_type* yylloc,...)` and stashing the location value for use in a rule. If the actual generated rule handling was handled in  `yylex (semantic_type* yylval, location_type* yylloc,...)` instead of `yylex (semantic_type* yylval,...)` I don't believe this would be an issue.

Unexpected behavior 3: There doesn't appear to be a straightforward way of setting other values of the location without derivation of the generated lexers and overriding the lex function. For example, setting filenames if you are using the bison-generated locations.

Most if not all of the above idiosyncrasies can be dealt with by redefining `YY_USER_ACTION` but my read of your documentation suggests that your would like to have automatic location tracking as a feature.

My suggestion for your consideration would be:

1. Have the generated rules be put into the appropriate yylex function for the options. That is, if locations are enabled, place them into`yylex (semantic_type* yylval, location_type* yylloc,...)`. This will allow location data to be used in rules.

2. Move the automatic location update functionality out of the yylex... functions and into the generated Lexer. To me, the issue with the location it is in now is that the information needed to appropriately set the **end** needs to come after the content is matched but _before_ the rule action code is handled. This is why `YY_USER_ACTION` was a popular place to handle location updates.  The messy part of this was that the code defined in `YY_USER_ACTION` was duplicated for each rule. It would seem that re-flex could put this in a more appropriate place in the generated Lexer after the content was matched but _before_ the rule actions were executed. To me, it also makes sense for the user to be able to override any automatic behavior which a virtual Lexer class method would suffice. For example from the documentation:

```
/**
  match is known at the call site so begin and end can be properly set. The 
  user can override for any custom behavior.
*/
virtual bool LEXER::update_locations(location_type* yylloc) {...}
```

```
virtual int LEXER::yylex (semantic_type* yylval, location_type* yylloc,...)
{
    static const reflex::Pattern PATTERN_INITIAL("(?m)(REGEX)");
    if (!has_matcher())
    {
      matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
      YY_USER_INIT
    }
    CODE
    while (true)
    {
      switch (matcher().scan() && update_locations(yyloc)) // or semantically equivalent
      {
        case 0:
          if (matcher().at_end())
          {
            return 0;
          }
          else
          {
            output(matcher().input());
          }
          YY_BREAK
        case 1:
          YY_USER_ACTION
          ACTION
          YY_BREAK
      }
    }
}
```

**Comment by genivia-inc** [comment]
Thanks for the details. Will take a look at this for the next release.

**Comment by genivia-inc** [comment]
Hypothetically your approach won't work well when `more()` or `less(n)` are used in one of the switch arms (i.e. the code specified in the lexer spec), because these affect the length of the match. In that case the reported end position stored in`llocp->last_column` will not line up with the actual match size, because `update_locations(yyloc)` is called too soon before `more()` or `less(n)` are called. Perhaps a minor detail. Also, I like the idea having a choice of user-defined positions update function or a built-in update function generated by reflex (but one that is corrected as you point out). Perhaps using an `#define` to allow the generated update code to be replaced. I'll explore that.

**Comment by genivia-inc** [comment]
I've implemented an updated bison-locations approach as suggested in v1.1.1.

**Comment by genivia-inc** [comment]
Hm. I think a small change needs to be made to v1.1.1, now that I am trying more examples. The ending column reported by the new `yylloc_update` Lexer method is the column after the match, not the last column of the match. So I will change the assignment to `yylloc.end.column = yylloc.begin.column + matcher().columns() - 1`, thus with one less. Everything else checks out fine. Please take a look if you agree.

**Comment by tegtmeye** [comment]
I'll check but it sounds correct.

Thanks again for doing this.
