### ISSUE TITLE
Backslashes in input filenames

### ISSUE THREAD

**Issue by pedro-lm** [Genivia/RE-flex#27]
When using re/flex on Windows with VisualC compiler and filenames containing native Windows path delimiters ('\\'), the delimiters are not escaped when output into the resulting files, e.g. `#line 9 "..\calc.l"`, which causes the compiler to complain, e.g. `..calc.l(43) : warning C4129: 'c' : unrecognized character escape sequence`. The similar happens with the macros `#REFLEX_OPTION_header_file`, `#REFLEX_OPTION_outfile` (maybe even some others I haven't noticed?).

**Comment by genivia-inc** [comment]
Interesting. I've made a few changes for the coming release iteration to emit `\\` for `\` in file paths.
