### ISSUE TITLE
Code block in rules section for all inclusive start conditions

### ISSUE THREAD

**Issue by Krantz-XRF** [Genivia/RE-flex#28]
According to the [documentation](https://www.genivia.com/doc/reflex/html/index.html#reflex-states), 

> %{
>  // Code for all inclusive states (INITIAL and A)
> %}

But as I tested, that code block is surrounded by a `switch` of `start()`, which makes that code block only be executed in start condition `INITIAL`. Is this a bug or an intensional design? If it's the latter, why is the documentation saying in a different way?

**Comment by genivia-inc** [comment]
Looks like a bug to me, because this block should be replicated in both the `INITIAL` and `A` states. Will take a look why this code is not replicated.

**Comment by genivia-inc** [comment]
A patch that fixes this:

~~~
*** reflex.cpp	2019-03-26 16:07:24.000000000 -0400
--- reflex-upd.cpp	2019-03-26 16:07:45.000000000 -0400
***************
*** 1378,1384 ****
          std::string code = get_code(pos);
          if (scopes.empty())
          {
!           section_2[0].push_back(Code(code, infile, lineno));
          }
          else
          {
--- 1378,1388 ----
          std::string code = get_code(pos);
          if (scopes.empty())
          {
!           for (Start start = 0; start < conditions.size(); ++start)
!           {
!             if (inclusive.find(start) != inclusive.end())
!               section_2[start].push_back(Code(code, infile, lineno));
!           }
          }
          else
          {
~~~
