### ISSUE TITLE
Matching empty expressions

### ISSUE THREAD

**Issue by Krantz-XRF** [Genivia/RE-flex#31]
It might be reasonable to match empty expressions, for empty expressions can have lookahead expressions, and e.g. can be used to pop start states from the stack. It seems RE-Flex does not support having an empty expression in the rules section. Will you ever consider adding such a feature? If not, is there any technical difficulty, and would you please offer some workaround method?

**Comment by genivia-inc** [comment]
Allowing for empty matches/expressions is inherently problematic for scanners, which may end up running infinite loops when no input is consumed. Therefore this feature is not enabled by default. However, the reflex matchers `reflex::Matcher` and `reflex::BoostMatcher` support empty matches and expressions using option `"N"` (nullable). `reflex::StdMatcher` does not support empty matches.

The reflex tool does not have an option right now to allow for nullable matches, but this easy to add as a feature to initialize the `Matcher` with option `N` in the generated `lex.yy.cpp` file.

If you and others believe this is a useful addition then let me add it, say with reflex specification option `%o nullable` perhaps.

**Comment by genivia-inc** [comment]
I forgot to mention, but option `"N"` does not apply to matcher `scan` operations, only to `matches` operations, so adding an option `%o nullable` to the scanner generator is a moot point.

Instead of enabling nullable scan matches, with all the potential pitfalls that come with it, why not replace the look-ahead pattern you mentioned but without the lookahead and simply use `less` to shorten the match to 0 length?

**Comment by Krantz-XRF** [comment]
To use the function `less` seems to solve this problem properly, and if it does, nullable scan matches are no longer needed. But I have just looked up the manual, and it seems that `less` does not accept `0` as a valid argument. 

> The `matcher().less(n)` method reduces the size of the matched text to `n` bytes. This method has no effect if `n` is larger than `size()`. The value of `n` should not be 0. The `matcher().less(n)` operation is often used in lexers and was introduced in Lex.

Anyway, I think you are right, nullable matches are error-prone, and using `less` is no safer. I may as well restructure my lexical grammar to avoid such needs.

**Comment by genivia-inc** [comment]
The function `less` can be called with zero. I'll explain in the manual why zero is usually not a good idea, but has its use when switching to another state for example.
