### ISSUE TITLE
Undefined Reference Linker Issue

### ISSUE THREAD

**Issue by suleimanmashini** [Genivia/RE-flex#32]
I keep trying to compile my lexer after using Reflex however, I keep getting an undefined reference error from the linker.
I have already install reflex and am using ubuntu.
The commands I run are:
``` reflex --main lex.flex```
```g++ lex.yy.cpp```
The error I get is:
``` /tmp/ccdCYfWd.o: In function `reflex::Input::get(char*, unsigned long)':
lex.yy.cpp:(.text._ZN6reflex5Input3getEPcm[_ZN6reflex5Input3getEPcm]+0x317): undefined reference to `reflex::Input::file_get(char*, unsigned long)'
/tmp/ccdCYfWd.o: In function `reflex::Input::init()':
lex.yy.cpp:(.text._ZN6reflex5Input4initEv[_ZN6reflex5Input4initEv]+0x67): undefined reference to `reflex::Input::file_init()'
/tmp/ccdCYfWd.o: In function `reflex::Pattern::Pattern(char const*, char const*)':
lex.yy.cpp:(.text._ZN6reflex7PatternC2EPKcS2_[_ZN6reflex7PatternC5EPKcS2_]+0x27): undefined reference to `vtable for reflex::Pattern'
lex.yy.cpp:(.text._ZN6reflex7PatternC2EPKcS2_[_ZN6reflex7PatternC5EPKcS2_]+0xc6): undefined reference to `reflex::Pattern::init(char const*)'
/tmp/ccdCYfWd.o: In function `reflex::Pattern::Pattern(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)':
lex.yy.cpp:(.text._ZN6reflex7PatternC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc[_ZN6reflex7PatternC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc]+0x18): undefined reference to `vtable for reflex::Pattern'
lex.yy.cpp:(.text._ZN6reflex7PatternC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc[_ZN6reflex7PatternC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc]+0x9b): undefined reference to `reflex::Pattern::init(char const*)'
/tmp/ccdCYfWd.o: In function `reflex::Pattern::~Pattern()':
lex.yy.cpp:(.text._ZN6reflex7PatternD2Ev[_ZN6reflex7PatternD5Ev]+0xf): undefined reference to `vtable for reflex::Pattern'
/tmp/ccdCYfWd.o: In function `reflex::Matcher::~Matcher()':
lex.yy.cpp:(.text._ZN6reflex7MatcherD2Ev[_ZN6reflex7MatcherD5Ev]+0xf): undefined reference to `vtable for reflex::Matcher'
/tmp/ccdCYfWd.o: In function `reflex::Matcher::Matcher<reflex::Pattern>(reflex::Pattern const&, reflex::Input const&, char const*)':
lex.yy.cpp:(.text._ZN6reflex7MatcherC2INS_7PatternEEERKT_RKNS_5InputEPKc[_ZN6reflex7MatcherC5INS_7PatternEEERKT_RKNS_5InputEPKc]+0x34): undefined reference to `vtable for reflex::Matcher'
/tmp/ccdCYfWd.o:(.data.rel.ro._ZTVN6reflex13AbstractLexerINS_7MatcherEE7MatcherE[_ZTVN6reflex13AbstractLexerINS_7MatcherEE7MatcherE]+0x50): undefined reference to `reflex::Matcher::match(int)'
/tmp/ccdCYfWd.o:(.data.rel.ro._ZTIN6reflex13AbstractLexerINS_7MatcherEE7MatcherE[_ZTIN6reflex13AbstractLexerINS_7MatcherEE7MatcherE]+0x10): undefined reference to `typeinfo for reflex::Matcher'
collect2: error: ld returned 1 exit status```

The contents of my lexer file are:
```
%top{
  #include <iostream>
  #include <sstream>
  #include <fstream>

  std::stringstream ss;

%}

LETTERS        [\xd8a1-\xd98a\xd991]
DIAC           [\xd98b-\xd990\xd992\xd993]

%%
DIAC+       {/* ignore diacritics */}
٠           {ss << "0";}
١           {ss << "1";}
٢           {ss << "2";}
٣           {ss << "3";}
٤           {ss << "4";}
٥           {ss << "5";}
٦           {ss << "6";}
٧           {ss << "7";}
٨           {ss << "8";}
٩           {ss << "9";}
\]           {ss << "[";}
\[           {ss << "]";}
\{           {ss << "{";}
\}           {ss << "}";}
ذاتي        {ss << "auto";}
حاذى_ك      {ss << "alignas";}
صحيص        {ss << "int";}
أعد         {ss << "return";}
حاول        {ss << "try";}
"."+|","+    {ss << std::string(text());}
LETTERS+    {ss << std::string(text());}


%%
 ```
Thanks for the help!

**Comment by suleimanmashini** [comment]
Nevermind, added the cpp files to the compilation from the lib folder to get it working.

**Comment by genivia-inc** [comment]
No need to compile all sources: just link libreflex with `g++ lex.yy.cpp -lreflex` when you have reflex installed, or `g++ lex.yy.cpp reflex/lib/libreflex.a` to statically link the library.
