### ISSUE TITLE
Support for Bison C++ Complete Symbols

### ISSUE THREAD

**Issue by Krantz-XRF** [Genivia/RE-flex#34]
It would be very nice if RE-flex supports the Complete Symbols feature of Bison (For detailed information, see [Section 10.1.6.2 Complete Symbols](https://www.gnu.org/software/bison/manual/bison.html#Complete-Symbols)). 

After some investigation, I found out that the lexer needs only a few tweaks to work well with this feature. Since `bison-cc` is already supported, we just need to remove the `yylval` parameter, and change the return type to `parser::symbol_type`. Actually, the only necessary feature for this support is the ability to specify the return type of `lex`.

**Comment by genivia-inc** [comment]
Interesting suggestion. I like it. Why not fork the project and give it a try?

Before creating a pull request, please consider executing these steps:
~~~
./clean.sh
./build.sh # make sure this works
cd tests; make -f Make; cd .. # make sure this works
./clean.sh
aclocal
autoheader
rm -f config.guess config.sub ar-lib compile depcomp install-sh missing
automake --add-missing --foreign
autoconf
automake
~~~

**Comment by Krantz-XRF** [comment]
I am currently working on this. It may take a while, for in a week I will have my mid-term exam. 😅 I expect this won't take long, though.

**Comment by genivia-inc** [comment]
Great. Looking forward to it.

**Comment by Krantz-XRF** [comment]
It's a little more complicated than I thought, but I think my version is usable now. Now I have a few questions:

1. I added 4 options: `bison-complete`, `token-type`, `exception` and `default-token`, and I don't know whether you like it. At first, I planned to make `token-type` work for all scanner types, but I gave up finally, in order not to break any working code. Currently the last 3 options work only if `bison-complete` is enabled;
2. Some short descriptions are added to the help message, but I don't know whether they are clear enough;
3. The manual is not updated, so these features are not described at all;
4. I have a tiny example/test case, and now I'm not sure whether and where to include that;
5. The windows build is left untouched, for I don't know which compiler I should use, though it should compile on Visual Studio 2017 and 2019 (as I tested on my machine);

Anyway, the changes are available in my forked repo. Should I create a pull request now or should I do some further modifications before that?

Some descriptions for those new options above:

1. `bison-complete`: the overall switch;
2. `token-type`: the return type of the `lex` method (or `yylex`), whose default value is `<bison-cc-namespace>::<bison-cc-parser>::symbol_type`;
3. `exception`: since the return type is complicated, we cannot just return 0 in the default rule, this option specifies the exception type to be thrown in the default rule;
4. `default-token`: another option is to return a default token in the default rule, the value of this option is written to the generated file unchanged. When this option is specified, no exceptions are thrown, and the option `exception` is ignored.

**Comment by genivia-inc** [comment]
A few questions/comments:

1. `exception` is this a type or a value? If this is a type, perhaps use `exception-type`? If this is a value, perhaps use `exception-token`?
2. For your 1), this approach you took makes sense.
3. For your 2) and 3), don't worry I will take a look at this. Options are described in more detail in the manual, so it makes sense to keep the help descriptions short. We should assume that folks are already familiar with Bison-complete to use these options. I will work on the manual to update it.
4. For your 4), I can take a look.
5. For your 5), don't worry. It is somewhat complicated to use VS to build the reflex tool and I'll work on that.

Please go ahead to create a pull request. Before doing so, make sure to follow the suggestions (it builds and the tests succeed to be built also.)

**Comment by genivia-inc** [comment]
Thanks a lot for your feedback and for improving reflex! You can rate reflex at https://sourceforge.net/projects/re-flex/reviews/ and that helps to inform others what is great and what needs improvement.
