### ISSUE TITLE
debug.cpp fails to compile under MinGW

### ISSUE THREAD

**Issue by donn** [Genivia/RE-flex#38]
Hey. While trying to get one of my projects to compile on Windows, I ran into a problem. Essentially, MinGW doesn't support `localtime_r`.

I can fix this by editing this line:
https://github.com/Genivia/RE-flex/blob/0b3a81b86e73268fdc0bba3b33fbdb511e4a7687/lib/debug.cpp#L46

and removing this part

`&& !defined(__MINGW32__) && !defined(__MINGW64__)`

MINGW does support the Windows API.

Should I PR this or is there some concern?

**Comment by genivia-inc** [comment]
No concerns here with the change.
