### ISSUE TITLE
Indent/dedent ignore

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#41]
I am trying to ignore the indentation before a /* comment.
Like in:
program:
        /* an indented comment */
    statement;

However:  ^\h+\i"/*"
doesn't same to get matched, only when I remove the \i it is matched, otherwise it matches the normal: ^\h+\i

But there is no method in matcher() to see if stops have been added or removed, which I want to ignore.
The only hack I can come up with is to copy the stops vector when I encounter a \n and restore that when I match ^\h+"/*" which seems a bit of overkill.

**Comment by genivia-inc** [comment]
To ignore comments (indented or not), it is simpler to use a negative pattern. See the Python `ptokens.l` example in the `examples` directory which has the pattern:

    (?^^(\f?\h*(#{any}*?)?\r?\n)+) // eat blank lines and comments, anchor ^ in (?^X)

Python has more "line joining" rules that require pushing and popping indent stops, but comments (when matched across multiple lines) can just be "eaten" away without affecting the indent stops. In your case this would be a negative pattern `(?^...)` that matches the start of a line `^` followed by white space `\h*` and a `/*...*/` comment that may span multiple lines:

    (?^^\h*/\*([^*]|(\*+[^*/]))*\*+\/)

**Comment by RuudRietvink** [comment]
This will not work for me, since I plan to allow nested comments, so it should not stop at the first */

**Comment by genivia-inc** [comment]
Then I suggest to define a start condition to transition to, to eat nested comments by keeping track of the nesting depth, something like this:

    int depth; // lexer class member or global var
    %x COMMENT

    <INITIAL>^\h*"/*"      { start(COMMENT); depth = 0; matcher().push_stops(); }
    <COMMENT>"*/"          { if (depth == 0) { start(INITIAL); matcher().pop_stops(); } else --depth; }
    <COMMENT>"/*"          { ++depth; }
    <COMMENT>.|\n    
    <COMMENT><<EOF>>       { return 0; } // should report an error here e.g. "EOF in comment"

See also `examples/indent.l`.

**Comment by RuudRietvink** [comment]
Yes, I did that. But the matcher().stops already has the comment indentation added to it (if new indent) or substracted (if dedent) or unchanged (if same indentation).
So, when I pop it, it still has the (iptional) comment indentation added.
That's why I need to copy the stops at the previous new-line, and restore it after the ^\h+/*

**Comment by genivia-inc** [comment]
Note that matching a pattern that has a `\I` or a `\j` in it changes the stops. No other pattern can change stops. So somewhere you have a pattern that indents/dedents before the comment is scanned, which causes the stops to change. Just adding a pattern that eats the indent and the comment together should work to avoid that.

**Comment by RuudRietvink** [comment]
Sorry for the long contents here.
Then why am I getting this, note the output line starting with 'hc' from debug output:

Lex:
```
%top{
#include "NateParser.tab.h"  /* Generated by bison. */
#include "location.hpp"  /* Generated by bison %locations. */
%}

%class{
  std::vector<size_t> prevStops;
  int depth;

  void includeFile()
  {
    depth++;
    if (depth > 99)
      exit(EXIT_FAILURE);           // max include depth exceeded
    const char *q = strchr(text(), '"');  // get ..."filename"
    char *file = _strdup(q + 1);     // get filename"
    file[strlen(file) - 1] = '\0';  // get filename
    FILE *fd;
	fopen_s(&fd, file, "r");
    free(file);
    if (!fd)
      exit(EXIT_FAILURE);           // cannot open file
    push_matcher(new_matcher(fd));  // push current matcher, use new matcher
  }

  bool endOfFile()
  {
    if (depth == 0)
      return true;                  // return true: no more input to read
    fclose(in());                   // close current input in() (a FILE*)
    pop_matcher();                  // delete current matcher, pop matcher
    depth--;
    return false;                   // return false: continue reading
  }
%}

%option bison-complete
%option bison-cc-namespace=yy
%option bison-cc-parser=parser
%option bison-locations
%option exception="yy::parser::syntax_error(location(), \"Unknown token.\")"
%option namespace=yy
%option lexer=Lexer
//%option unicode
%option tabs=4
%option debug
//%option fast

%x INLINE_COMMENT

%%

^\h+"//".*\n  // ignore indent changes
"//".*\n      /* ignore */
^\h+"/*"      std::cerr << "hc " << matcher().stops().size() << " " << matcher().last_stop() << std::endl;  // ignore indent changes
              start(INLINE_COMMENT);            // continue w/o indent matching
"/*"	     start(INLINE_COMMENT);            // continue w/o indent matching
<INLINE_COMMENT>{
"*/"        start(INITIAL);                   // go back to the initial scanning state
[^*/]+|.|\n   /* ignore */
}

^\h+          std::cerr << "h " << matcher().stops().size() << " " << matcher().last_stop() << std::endl; /* ignore */
^\h*\i        std::cerr << "+ " << matcher().stops().size() << " " << matcher().last_stop() << std::endl; return yy::parser::make_BEGIN(location()); // indent
^\h*\j        std::cerr << "- " << matcher().stops().size() << " " << matcher().last_stop() << std::endl; return yy::parser::make_END(location());   // dedent
\j            std::cerr << "-- " << matcher().stops().size() << " " << matcher().last_stop() << std::endl;  return yy::parser::make_END(location());   // dedent, for each extra indent level on the same line
(?^\\\n\h+)   /* lines ending in \ will continue on the next line
                 without affecting the current \i tab positions */

^\h*include\h*\".*?\"    includeFile();

"program"	  return yy::parser::make_PROGRAM(location());
":"			  return yy::parser::make_COL(location());

\n            prevStops = matcher().stops();
\h+           // skip space

[$]?[\p{Alpha}]([-\p{Word}]*[\p{Alnum}])?  return yy::parser::make_IDENTIFIER(str(), location());
[-+]?[0-9]+(\.[0-9]+)?([eE][-+]?[0-9]+)?   return yy::parser::make_NUMBER(str(), location());

<<EOF>>  if (!matcher().stops().empty())
		 {
		     matcher().stops().pop_back();
			 return yy::parser::make_END(location()); 
		 }
		 else if (endOfFile()) 
		 {
		     return yy::parser::make_EOF(location());
		 }

.        std::cerr << str() << (int)str()[0] << std::endl; return yy::parser::make_ERR(location());

%%
```

With input:
```
  program:
    hoi // comment comment
          /* comment 
	   line */
    end
```
And output:
```
--accepting rule at line 69 ("  ")
+ 1 2
--accepting rule at line 77 ("program")
--accepting rule at line 78 (":")
--accepting rule at line 80 ("
")
--accepting rule at line 69 ("    ")
+ 2 4
--accepting rule at line 83 ("hoi")
 Id hoi
--accepting rule at line 81 (" ")
--accepting rule at line 55 ("// comment comment
")
--accepting rule at line 56 ("          /*")
hc 3 10
--accepting rule at line 64 (" comment
           line ")
--accepting rule at line 62 ("*/")
--accepting rule at line 80 ("
")
--accepting rule at line 70 ("    ")
- 2 4
--accepting rule at line 83 ("end")
5.4-5: syntax error, unexpected identifier, expecting end block
Oops
```

**Comment by genivia-inc** [comment]
Because the rule

    ^\h+"/*"

still affects the indent stops. I should have clarified this better: any pattern that is longer than the indent/dedent rules still adds a stop, not just rules with `\i` and `\j`.

This other rule also adds a stop:

     ^\h+"//".*\n

Make this a negative pattern to avoid that.

I'll take a closer look at the matcher logic to figure out ways for improvement and to explain the logic in the manual. In general, matching indent/nodent/dedent is a tricky business to automate.

PS. I can think of one way to avoid the problem you describe and I'll investigate if that is a viable solution. Basically, patterns that do not overlap with `\i`-patterns and `\j`-patterns should not affect the indent stops. Let's see if that can be done.

**Comment by genivia-inc** [comment]
Note that the rules can be modified to make indent/dedent work properly by using a trailing context (`/`) in a negative pattern to eat the white space before a comment:

    (?^^\h+/"/*")  // eat white space before /*-comments without affecting indent stops
    (?^^\h+/"//")  // eat white space before //-comments without affecting indent stops
    "/*"           start(INLINE_COMMENT);
    "//".*\n       // ignore comment

The two negative patterns at the top eat the white space before the `/*` and the `//` without affecting the indent stops that are in effect.

**Comment by RuudRietvink** [comment]
Yes, that's the best solution, thanks.
