### ISSUE TITLE
assert on windows

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#43]
With every new release I still have to change this line in pattern.cpp:
`
  if (c <= 255 && 
      std::isalpha(c) && (opt_.i || is_modified('i', modifiers, loc)))
`

because isalpha asserts in debug mode.
You said you didn't want to change it because of optimization, but the extra comparison is nothing compared to the function calls and their contents.

**Comment by genivia-inc** [comment]
Ah, I think the problem is the `c = compile_esc(loc + 1, chars)` that may return `c>256`. I don't recall saying that it wasn't necessary to change because of optimization, but rather I may have looked at the wrong line that looks the same as you report but which doesn't have this issue.

**Comment by genivia-inc** [comment]
Fixed.
