### ISSUE TITLE
peek() in code block of rules section

### ISSUE THREAD

**Issue by ivan-khudyashev** [Genivia/RE-flex#45]
Hello, all. First of all thanks for amazing tool!! It's so cool! :)

Is it possible use peek() method for some rule?
When I use it as `char next_char = matcher().peek();`
 then get error:
`error: ‘int reflex::AbstractMatcher::peek()’ is protected within this context`

Though if I use `char next_char = matcher().rest()[0]` - all good.
I afraid that rest() method need more time consumption.

**Comment by genivia-inc** [comment]
Great question. I would not recommend use `matcher().rest()[0]` because it consumes all of the remaining input. It looks like `peek()` was placed in the protected section rather than the public section as was originally intended. So moving `peek()` further up in `reflex/absmatcher.h` to make it public should resolve this problem. I tried it and it passes all tests. Will fix this in an upcoming update.

**Comment by ivan-khudyashev** [comment]
Strange. Moving up for `peek()` don't work for me. It return 0 all time.
But anyway, it's excellent, that it will fix in next releases!

**Comment by genivia-inc** [comment]
It does work. Try for example:

```
%%
x   std::cout << (char)matcher().peek() << std::endl;
.|\n
%%
```

This prints the character after an `x` in the input, without consuming that character.

Or this example, that duplicates the character after an `x`:

```
%%
x   std::cout << "x" << (char)matcher().peek() << std::endl;
%%
```

Note that the "default rule" copies the rest of the input.

I moved `peek()` after `unput(char c)` in `absmatcher.h`. Make sure to rebuild and reinstall reflex.

**Comment by ivan-khudyashev** [comment]
Yes. That example work. But probably I somethig miss :( and my example don't work:
```
%top{
    /* Headers */
    #include <iostream>
    #include <string>
%}

 /* Options */
%o matcher=reflex
%o noyywrap

 /* Lexer States */
%x SCURLY_BRACE

 /* User Actions and other global def */
%{
 #define RE_YY_USER_ACTION std::cout << "<--" << str() << "s-->" << std::endl;
%}
H_SP                                \u{0020}
H_LF                                \u{000A}
H_CR                                \u{000D}
WHITESPACE                          [\t\v\f]|{H_SP}
LINETERMINATOR                      (?:{H_CR}{H_LF}?)|{H_LF}
NAME                                (?:[_[:alpha:]])\w*
%%
<*>{WHITESPACE}+                       { RE_YY_USER_ACTION return 1; } /* skip Whitespaces */
 /* Curly brace states */
"{"                                 {
                                        RE_YY_USER_ACTION
                                        char next_char = 1;
                                        next_char = (char)matcher().peek();
                                        //next_char = this->matcher().rest()[0];
                                        std::cout << "\t\t next char = " << next_char << "(" << (int)next_char << ")\n";
                                        if(next_char == ' ' || next_char == '\t' || next_char == '\n' || next_char == '\r') {
                                            this->push_state(SCURLY_BRACE); std::cout << "T_CODEBLOCK_HEAD\n"; return 1;
                                        }
                                        std::cout << "P_LCBRACE\n"; return 1;
                                    }
<SCURLY_BRACE>[^} \n\r\t]+          { RE_YY_USER_ACTION std::cout << "T_CODEBLOCK_WORD\n"; return 1; }
<SCURLY_BRACE>"}"                   { RE_YY_USER_ACTION std::cout << "P_BLOCKCODE_TAIL\n"; this->pop_state(); return 1;  }
"}"                                 { RE_YY_USER_ACTION std::cout << "P_LCBRACE\n"; return 1;  }
{NAME}                              { RE_YY_USER_ACTION std::cout << "T_NAME\n"; return 1; }
<<EOF>>                             { RE_YY_USER_ACTION std::cout << "EOF\n"; return 0; }
<*>{LINETERMINATOR}                 { std::cout << "<--CR-->\n" << "LINETERMINATOR\n"; return 1; }
.                                   { RE_YY_USER_ACTION std::cout << "T_UNKNOWN\n"; return 1; }
%%
int main()
{
    while(Lexer().lex());
    return 0;
}
```

**Comment by genivia-inc** [comment]
Thanks, I'll test this example. Note that another way (perhaps better) is to detect spacing after a `{` is to use a "trailing context" (lookahead):

```
%%
"{"/[ \t\r\n]    // ... rule for { followed by white space [ \t\r\n] (could use \s to match white space, actually)
"{"              // ... rule for { not followed by white space
%%
```

**Comment by genivia-inc** [comment]
Your while-loop in `main` creates a new `Lexer` every iteration. That's not what you had intended, I'm sure. Change to:

```
Lexer lexer;
while (lexer.lex())
  continue;
```

**Comment by ivan-khudyashev** [comment]
> Your while-loop in `main` creates a new `Lexer` every iteration. That's not what you had intended, I'm sure. Change to:
> 
> ```
> Lexer lexer;
> while (lexer.lex())
>   continue;
> ```
🤦‍♂ of course, this silly mistake 
But I found out where I was wrong.
There are 2 cases when peek() don't work such as I want.
1. If use debug mode  for RE/flex.
2. If use text() for output. If I use str() - it's OK, but if I use text(), then peek() return 0.

**Comment by ivan-khudyashev** [comment]
> Thanks, I'll test this example. Note that another way (perhaps better) is to detect spacing after a `{` is to use a "trailing context" (lookahead):
> 
> ```
> %%
> "{"/[ \t\r\n]    // ... rule for { followed by white space [ \t\r\n] (could use \s to match white space, actually)
> "{"              // ... rule for { not followed by white space
> %%
> ```
O, thank. I think about this case. But my example is very simplyfied version of more big project. And in context of this project LOOKAHEAD with peek() more elegant and clear decision.

**Comment by ivan-khudyashev** [comment]
@genivia-inc Thank you very much for help and especially for cool RE/flex tool!
