### ISSUE TITLE
Incrementally parse text

### ISSUE THREAD

**Issue by ofersadgat** [Genivia/RE-flex#46]
Hi, first, thanks for all the work! I have a question: I have a base loop like follows:

(pseudocode)
```
int result;
yyscan_t scanner;
yy_lex_init(&scanner);
while (1){
    int descriptor = select(fd_set);
    char buffer[1024];
    int amount = read(descriptor, &buffer);
    yy_scan_bytes(buffer, amount, scanner);
    int parseResult = yy_parse(scanner, &result);
    printf("[Result (%d)]: %d\n", parseResult, result);
}
```

```
[ \t]   ; // ignore all whitespace
[0-9]+\.[0-9]+  {yylval->fval = atof(yytext); return T_FLOAT;}
[0-9]+      {yylval->ival = atoi(yytext); return T_INT;}
\n      {return T_NEWLINE;}
"+"     {return T_PLUS;}
"-"     {return T_MINUS;}
"*"     {return T_MULTIPLY;}
"/"     {return T_DIVIDE;}
"("     {return T_LEFT;}
")"     {return T_RIGHT;}
```

```
calculation: line { *(int*)out = $1; $$ = $1; YYACCEPT ; }
;

line: T_NEWLINE
    | mixed_expression T_NEWLINE { $$ = (int)$1; }
    | expression T_NEWLINE { $$ = $1; }
    | T_QUIT T_NEWLINE { printf("bye!\n"); exit(0); }
;

mixed_expression: T_FLOAT                        { $$ = $1; }
      | mixed_expression T_PLUS mixed_expression     { $$ = $1 + $3; }
      | mixed_expression T_MINUS mixed_expression    { $$ = $1 - $3; }
      | mixed_expression T_MULTIPLY mixed_expression { $$ = $1 * $3; }
      | mixed_expression T_DIVIDE mixed_expression   { $$ = $1 / $3; }
      | T_LEFT mixed_expression T_RIGHT      { $$ = $2; }
      | expression T_PLUS mixed_expression       { $$ = $1 + $3; }
      | expression T_MINUS mixed_expression      { $$ = $1 - $3; }
      | expression T_MULTIPLY mixed_expression   { $$ = $1 * $3; }
      | expression T_DIVIDE mixed_expression     { $$ = $1 / $3; }
      | mixed_expression T_PLUS expression       { $$ = $1 + $3; }
      | mixed_expression T_MINUS expression      { $$ = $1 - $3; }
      | mixed_expression T_MULTIPLY expression   { $$ = $1 * $3; }
      | mixed_expression T_DIVIDE expression     { $$ = $1 / $3; }
      | expression T_DIVIDE expression       { $$ = $1 / (float)$3; }
;

expression: T_INT               { $$ = $1; }
      | expression T_PLUS expression    { $$ = $1 + $3; }
      | expression T_MINUS expression   { $$ = $1 - $3; }
      | expression T_MULTIPLY expression    { $$ = $1 * $3; }
      | T_LEFT expression T_RIGHT       { $$ = $2; }
;
```

My question is how can I get yy_parse to work without resetting state between every yy_scan_bytes call? So if select returns `1 + ` on 1 call, then `1` the next and then the stream closes, I should get the result 2. Is this possible?

Thanks again!

**Comment by genivia-inc** [comment]
Good question. When an input stream is exhausted, the lexer ends unless `wrap()` (`yywrap()` in Flex mode) is defined that opens a new stream to continue scanning without interruption. See `examples/readline.l` for an example on how `yywrap()` is used to read the next line with `readline`. Note that this example sets `in(linen)` to specify a string line to read by the lexer. Replacing this with `yy_scan_bytes` works too.

**Comment by ofersadgat** [comment]
Thanks for the help! As you can see from the base loop, data comes from calling select followed by read meaning that there are two options: 

1. call parse and pass it the socket (as you've illustrated in your example) or 
2. make parse able to return and incrementally update. 

1 is currently extremely difficult given the layout of the existing code, so I was wondering if there is a way to make 2 work. Thanks again for your time and help!

**Comment by genivia-inc** [comment]
For #1 you just need to assign `descriptor` (and maybe also `fd_set`) to the `scanner` instead of at `%init`, if you can't change the loop much:

    scanner.descriptor = descriptor;

To do so, make the members `public` in the lexer class:

```
%class{
  public:
    int descriptor;
    char buffer[1024];
    virtual int ywrap()
    { ... }
%}
```

The loop would be:

```
int result;
yyscan_t scanner;
yy_lex_init(&scanner);
while (1){
    scanner.descriptor = select(fd_set);
    int parseResult = yy_parse(scanner, &result);
    printf("[Result (%d)]: %d\n", parseResult, result);
}
```

All the other work to incrementally read the input into a buffer is done in `yywrap()`.

**Comment by genivia-inc** [comment]
Another possibility is to defined a `LexerInput(s,n)` method in your class that incrementally extracts input from a data source. The method fills a string buffer parameter `s` up to the size parameter `n` and returns the number of bytes placed in buffer `s`. This virtual method is defined in `FlexLexer` and conforms to Flex behavior, see "Switching input sources" (to the end of that section) in the RE/Flex manual and Flex manuals on `LexerInput`.

**Comment by ofersadgat** [comment]
Yes, thanks for the response. From what I've experimented with, "Switching input sources" works only if you allow the call to block the thread. I.e. it doesnt seem to work if yywrap returns 0 and then I pass in more data when lexing isnt on the call stack. Is that correct? the idea is that it is difficult to embed the event loop inside the lexer so what I would like is to have the event loop outside the lexer and simply pass it data as it becomes available:

```
while (1){
   fetch data
   feed data to lexer
   does scanner have a parse (i.e. was YYACCEPT called)?
   if yes
      callback(result)
```

is this possible? i apologize if I am not good at making myself clear. sorry for any confusion and thanks for the help!

**Comment by genivia-inc** [comment]
I am not convinced that your approach is feasible the way you describe. Assuming you're using Bison, `yyparse()` does not complete until the input is fully parsed.

**Comment by genivia-inc** [comment]
This is really a limitation of the parser, that calls the lexer repeatedly for more tokens until EOF. You could use two threads to feed more data, using a mutex lock and condition variable to signal that more data is available in a buffer/queue. The parser runs in one thread, internally invoking the lexer. The other thread feeds the data. To do so, you will need to use `yywrap()` to read that data and wait (i.e. block) there when the data is not available. A standard queue buffer should work with mutex and two condition variables (queue empty/full).
