### ISSUE TITLE
| over multiple lines

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#52]
Breaking up a regex with a | over multiple lines messes up the line numbering of following lines:
```
<LOOP>{
\bwhile\b|
(?^^\h+/while\b)	return yy::parser::make_WHILE(location());
}
```

**Comment by genivia-inc** [comment]
Doesn't appear to mess up:
```
%%
abc     |
def     ECHO;
%%
```
`lex.yy.cpp`:
```
          case 1: // rule at line 2: abc
          case 2: // rule at line 3: def
#line 3 "test2.l"
ECHO;
            break;
```
The `|` should be placed after the pattern, otherwise reflex throws a syntax error.

**Comment by RuudRietvink** [comment]
Yes, I thought it helped to solve the issue. All my line nrs are 1 or 2 off.
