### ISSUE TITLE
%option tabs=2

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#53]
The tabs option is not inherited for new Matchers when parsing include files.

`push_matcher(new_matcher(fd));  // push current matcher, use new matcher`

**Comment by genivia-inc** [comment]
Here is a straightforward patch.

In `include/reflex/absmatcher.h` add to the `AbstractMatcher` public methods:
```
  /// Set tab size 1, 2, 4, or 8
  void tab(char n)
  {
    if (n == 1 || n == 2 || n == 4 || n == 8)
      opt_.T = n;
  }
  /// Returns current tab size 1, 2, 4, or 8
  char tab()
  {
    return opt_.T;
  }
```
And in `include/reflex/abslexer.h` change:
```
  /// Returns a new matcher for the given input.
  virtual Matcher *new_matcher(
      const Input& input,     ///< reflex::Input character sequence to match
      const char *opt = NULL) ///< options, if any
    /// @returns pointer to new reflex::AbstractLexer::Matcher.
  {
    char tab[4] = "T=n";
    return new Matcher(matcher().pattern(), input, this, opt ? opt : (tab[2] = '0' + matcher().tab(), tab));
  }
```

**Comment by RuudRietvink** [comment]
so you have all the code, but are not going to implement it?

**Comment by genivia-inc** [comment]
This is on the **TODO** list for upcoming releases. Because this is not really a bug, why make it a top priority? BTW. `tab()` will be named `tabs()`.

**Comment by RuudRietvink** [comment]
You might have said that in the first place.

**Comment by genivia-inc** [comment]
Agreed. I should keep the world from falling apart due to a teeny minor software usage problem and I so am obligated to immediately respond with a patch and a full software release cycle 🙃 ¯\_(ツ)_/¯

**Comment by RuudRietvink** [comment]
Not what I meant. When you gave the code for a patch, you could have mentioned that it was on a to-do list for a next release. Now it was unclear whether it would be fixed or not.
Also sarcasm is not justified here.

**Comment by genivia-inc** [comment]
Um..., not sure what you mean here, but why would I spent time submitting a patch as a workaround to get this specific feature that you wanted? If something gets patched it eventually will be folded in the main branch. Why would it not? Unless the patch is somehow terrible, unusable, or breaks other features.

**Comment by genivia-inc** [comment]
Ran the tests & more. New version 1.3.1 is released with the anticipated updates.
