### ISSUE TITLE
Dynamic exception specifications are deprecated/removed in newer c++ standards

### ISSUE THREAD

**Issue by fkloiber** [Genivia/RE-flex#6]
The code uses dynamic exception specifications. Those are deprecated since C++11 and are removed in C++17. Meaning the generated code won't compile in C++17 mode.

**Comment by genivia-inc** [comment]
Ah, yes that's regrettable. Removing these comes at a loss of self-documentation. But anyway, I removed the dynamic exception specifications from the new 1.0.0 release. Thanks for the feedback.
