### ISSUE TITLE
How to get one token after another

### ISSUE THREAD

**Issue by DaOnlyOwner** [Genivia/RE-flex#60]
Hello,

Right now when calling Lexer::lex(), the whole input is scanned. Is there an option to just scan one token and return, for example by refactoring the code inside Lexer::lex() (inside while(true)) into a function that can also be called by client code?  

Best regards

**Comment by genivia-inc** [comment]
Good point. The scanner reads 16K input and then chunks of 8K to buffer, not the whole input at once (unless Perl regex matching is used with Boost Regex).

I think you are looking for reflex option `-I` (`--interactive). This option "eats input" one character at a time until a token matches.

Note however that long patterns may still eat more input than may be strictly needed when the pattern has an ending that can only be decided by looking further ahead in the input, for example `a+(b*c)?` reads `aaaax` until the first `x` to return a match for `aaaa` but reads `aaaabbbbbbbbbx` to return a match for `aaaa` and places `bbbbbbbbbx` back on the input to be matched by another rule.
