### ISSUE TITLE
Incorrect return type in documentation involving --bison-complete

### ISSUE THREAD

**Issue by Krantz-XRF** [Genivia/RE-flex#61]
In section [Bison and thread-safety](https://www.genivia.com/doc/reflex/html/#reflex-bison-mt-safe), it seems that method `lex` always has `int` as its return type, yet as I remember, `lex` should return `<parser>::symbol_type` when provided option `--bison-complete`. (Possibly some typo in the last few lines?)

**Comment by genivia-inc** [comment]
The `parser::symbol_type` is returned by `lex` with option `--bison-complete`, for example:
~~~
$ cd reflex/examples
$ make -f Make flexexample11xx
$ head -n27 scanner.cpp | tail -n1
#define REFLEX_OPTION_token_type          yy::parser::symbol_type
$ head -n139 scanner.cpp | tail -n1
yy::parser::symbol_type yy::scanner::yylex()
~~~
In this example we use namespace `yy` for `parser` and `scanner`.

Similar output is produced for `reflexexample11xx` for the `lex` method.

Note that the `lex` return type can be overridden with option `--token-type`.

**Comment by genivia-inc** [comment]
I see now that you are referring to the table in the documentation. I will update the documentation section "Bison and thread-safety".

**Comment by Krantz-XRF** [comment]
Yes, I was referring to the table in the documentation. Actually, I participated in writing that part of RE-flex (the `--bison-complete` part); I just meant that the documentation might need some correction.

Anyway, since you are going to update the documentation, I think this issue can be closed now.
