### ISSUE TITLE
<<EOF>> doesn't work right in case-insensitive mode

### ISSUE THREAD

**Issue by Stevie-O** [Genivia/RE-flex#62]
`<<EOF>>` is treated as a regex that is special-cased in several places.  When `%option case-insensitive` is in effect, it's rewritten as `<<[Ee][Oo][Ff]>>` and loses its special powers.

Patch coming momentarily.

**Comment by genivia-inc** [comment]
Thanks for the feedback. I'll update reflex in version 1.5.5. It requires only a minor change to fix this issue.
