### ISSUE TITLE
reflex 1.6.4: flex compatibility broken WRT %top{ ... %} vs. %top{ ... }

### ISSUE THREAD

**Issue by mandree** [Genivia/RE-flex#68]
Greetings,

there is a flex incompatibility with reflex 1.6.4 under --flex, affecting `%top{`. 
GNU flex expects `}` as the closing terminator, RE-flex expects `%}` (both per documentation, and per observed behaviour).

Using `%top{ ... %}` in GNU flex input leaves a stray `%` in the source code, flex succeeds, but compilation of the resulting generated lexer usually fails.
Using `%top{ ... }` in RE-flex causes an error `../example_lex.l:1: error: %% section ending encountered inside an action` and does not cause a lexer to be generated.

A workaround is adding a `// \` comment on a line before `%}`. This is incompatible with flex inputs that need to support C89 compilers, unless the latter support `//`-style single-line comment as an extension) - but should work with C99, C11, C++11, because line merging happens in the 2nd phase of compilation _before_ replacing comments by one space. Note that clang 8...10 by default enable _`-Wcomment`_ and issue a _bogus_ multi-line comment warning, and under `-Werror` or `-pedantic-errors`, incur an unwarranted compilation failure. GCC 9.2.0 seems OK.

```
%top{
#include "config.h" /* ... or whatever else you need */
// \
%}
```

Tested GNU flex versions: 2.5.37, 2.6.4, all on FreeBSD 12.1-RELEASE-p3 amd64.

FreeBSD bug filed here
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245006 I'll let our standards/toolchain guys forward this to LLVM.

**Comment by genivia-inc** [comment]
Thanks for reporting this. Either a `%}` or a `}` should be acceptable to terminate a `%top{` block. For some reason this difference with Flex was overlooked. Will update reflex soon to address this.

**Comment by genivia-inc** [comment]
Updated to 1.6.5 to permit `}` as closing marker for `%top{`, `%class{`, and `%init{` code blocks.
