### ISSUE TITLE
False warnings about rule subsummation

### ISSUE THREAD

**Issue by bouncepaw** [Genivia/RE-flex#70]
For example, I have these rules:

```lex
%s A

%%

// match anytime
"a"    push_state(A);
// match only in state A
<A>"b" pop_state();
// match in any state besides A
"b"    printf("b found");
```

When I compile, it would produce this warning:

```
file.l:line: warning: rule cannot be matched because a previous rule subsumes it,
perhaps try to move this rule up?
```

I think it's wrong because the second rule subsumes the third one *only* when the `A` start condition is on. The program works as intended though.

**Comment by genivia-inc** [comment]
You're using an inclusive start condition state `A`, which means that both the `INITIAL` state and the `A` state are active to match the third rule for `"b"`.

This means that the third rule is subsumed by the second rule.

Perhaps you meant to use an exclusive start condition state:
~~~
%x A
~~~

**Comment by bouncepaw** [comment]
Hmm yeah, there's no issue with the states 🤔 

Actually, the behaviour I wanted to achieve is more like ‘flags’. Perhaps, it should be a different start condition type.

```lex
%f A

%%

// matches in state A or any other.
"a"       push_state(A);
// matches in state A only.
<A>"b"    printf("b A");
// matches in any state but A.
"b"       printf("b ^A");
```

They work like that: if there are two patterns `<x>y` and `y` where `x` is a flag start state then the first one matches when the state is on and the second one matches when the state is off.

It may come in handy when you have a long list of rules and want to change them for a little time without copying all the rules for the new exclusive state.

Nevertheless, this behaviour can be easily obtained by using boolean variables and some ifs:

```lex
%f A

%%

"a"       push_state(A);
"b"       {
  if (flagA) printf("b A");
  else printf("b ^A");
}
```

Being able to write these flags on the left is just handy though not really necessary. I'll go on with the ifs.

**Comment by genivia-inc** [comment]
~~~
// matches in state A or any other.
"a"       push_state(A);
// matches in state A only.
<A>"b"    printf("b A");
// matches in any state but A.
"b"       printf("b ^A");
~~~
You can already do this by making start condition state `A` exclusive with `%x A` for the example above. If you want to keep `A` inclusive, then you can use negation (which does not exist in Flex but only RE/flex) to remove certain start condition states from rules. For example:
~~~
// matches in state A only.
<A>"b"    printf("b A");
// matches in any state but A.
<^A>"b"       printf("b ^A");
~~~

**Comment by genivia-inc** [comment]
One more last thing: avoiding problems with start condition states is important. At least we get warnings about rule subsumption, like Flex does. To better understand what you were hinting at in your last example:
~~~
%f A

%%

"a"       push_state(A);
"b"       {
  if (flagA) printf("b A");
  else printf("b ^A");
}
~~~
In this case a mechanism with flags can help as you point out, without using start condition states. Note that you can declare such flags in your lexer class defined with `%class` and initialized with `%init`.
