### ISSUE TITLE
filename field is nullptr

### ISSUE THREAD

**Issue by RuudRietvink** [Genivia/RE-flex#71]
The filename field in the position struct in the location struct is always nullptr.
Do I need some option to have it filled?

**Comment by genivia-inc** [comment]
Indeed, the `yy::position` class in `location.hh` has a `std::string*` filename member:
~~~
    /// File name to which this position refers.
    std::string* filename;
    /// Current line number.
    unsigned line;
    /// Current column number.
    unsigned column;
~~~
The Bison parsers calls `yy::Lexer::yylex(yy::parser::semantic_type& yylval, yy::location& yylloc)`.
In turn, this `yylex` lexer function calls `yylloc_update`, a function generated by reflex that updates the location info when scanning a token:
~~~
  virtual void yylloc_update(yy::location& yylloc)
  {
    yylloc.begin.line = static_cast<unsigned int>(matcher().lineno());
    yylloc.begin.column = static_cast<unsigned int>(matcher().columno());
    yylloc.end.line = static_cast<unsigned int>(matcher().lineno_end());
    yylloc.end.column = static_cast<unsigned int>(matcher().columno_end());
  }
~~~
The Bison parser creates `yy::location` objects and stores them on its stack.

I could not find anything in the Bison documentation on how to set the filename. Also the Bison-generated source code is quite opaque with respect to `yy::location`. There is no filename member access in the code as far as I can tell.

However, you are free to define error functions to report parsing errors. Your error function can report the error location with the filename of the file(s) that you opened. You should keep track of files that are opened anyway, using a stack of filenames in addition to a stack of Flex "scanner buffers" (i.e. reflex matchers) when switching between input sources, e.g. to handle `#include` and similar import statements.

**Comment by genivia-inc** [comment]
Today's reflex v2.1.0 update allows you to set the `filename` member of locations via the `filename` member of the lexer class generated with options `bison-complete` and `bison-locations`, see the updated manual section here:

https://www.genivia.com/doc/reflex/html/#reflex-bison-complete-locations

I've also added an extensive "Mini C" example to v2.1.0 that uses this member:

https://github.com/Genivia/RE-flex/blob/master/examples/minic.y

Thank you for your feedback!
