### ISSUE TITLE
Shift JIS support

### ISSUE THREAD

**Issue by Anonym271** [Genivia/RE-flex#73]
I want to write a small scanner that should tokenize a (self-defined) scripting language. However, some of the files to tokenize are saved in Shift JIS format. 

The problem is now, that Shift JIS contains some characters that can be misinterpreted as escape sequences when using other encodings (as described in [this](https://lists.gnu.org/archive/html/help-flex/2001-05/msg00017.html) post).
So if I use the regex `\"(\\.|[^"\\])*\"` as a string matching pattern some strings containing japanese text will not be recognized correctly.

Is there any option to tell my lexer to use Shift JIS encoding (like `%option unicode`)? Or do I have to convert them to unicode before lexing?

**Comment by genivia-inc** [comment]
Thank you for your feedback and comments.

Shift JIS encodes the Japanese character set with one or two bytes. This differs from the pre-defined "code pages" explained [here](https://www.genivia.com/doc/reflex/html/index.html#regex-input-file) in the user guide that assumes one byte. A custom code page would work for [CP932](https://en.wikipedia.org/wiki/Code_page_932_(Microsoft_Windows)) for example. Reading all this, I get the impression that these encodings and their differences with Shift JIS are apparently confusing, certainly when you see this [dense network of related encodings!](https://en.wikipedia.org/wiki/Shift_JIS#/media/File:JIS_and_Shift-JIS_variants.svg)

There are two options to handle this:

1. we extend RE/flex file encodings to byte pairs and implement a Shift JIS table;
2. or the Shift JIS encoded input file content has to be converted on the fly to UTF-8 (in memory), similar to the way the Java tokenizer example works (it translates embedded `\uxxxx` to Unicode in memory before scanning).

Pro/cons: 1) above is more attractive as more users will likely benefit, but it requires a new design of the `reflex::Input` class to handle double byte translations to Unicode. 2) is relatively simple if a library exists that can be used to perform the translation in memory. Are you aware of such a library?

And this poses another question: would Shift JIS be sufficient to cover, or are there other popular Japanese character encodings that would be necessary to handle?

**Comment by genivia-inc** [comment]
All things considered, your best bet is to implement this:

> 2. or the Shift JIS encoded input file content has to be converted on the fly to UTF-8 (in memory), similar to the way the Java tokenizer example works (it translates embedded \uxxxx to Unicode in memory before scanning).

Because there are so many variants and it is not clear to me which of these encodings is widely used, I am reluctant to implement this as a bullt-in feature in RE/flex.

**Comment by Anonym271** [comment]
Okay, Thank you very much for your advise. I will try to find a conversion library.
