### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#76]
Section "Patterns / Trailing context" has a typo: "Flex "trailing context" φ/ψ matches a pattern φ only when followed by the lookahead pattern φ." should be "Flex "trailing context" φ/ψ matches a pattern φ only when followed by the lookahead pattern ψ", I think.

**Comment by genivia-inc** [comment]
Good catch. Thanks for reporting this. I will updated the online documentation right away. The change will also be folded into the next RE/flex release update coming soon.
