### ISSUE TITLE
In Flex compatibility mode IN_HEADER should be yyIN_HEADER 

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#81]
I noticed this just by chance (I don't use this define) but in Flex compatibility mode and without specifying a symbol prefix, RE/flex puts a `#define IN_HEADER 1` in the generated header file, while Flex uses `#define yyIN_HEADER 1`. I thin the only purpose of this define is compatibility with Flex, thus it is maybe worth using the exact same name.

**Comment by genivia-inc** [comment]
Good catch! I had seen this in passing when updating the header output, but didn't spent sufficient attention to it and forgot about it.

**Comment by genivia-inc** [comment]
Fixed in v2.1.4.
