### ISSUE TITLE
Matching characters NOT in a Unicode character class.

### ISSUE THREAD

**Issue by rljacobson** [Genivia/RE-flex#82]
I am trying to understand a particular line of code. In the `parse_escape()` method of the `Pattern` class there is code to parse the escape sequences for Unicode character classes. [Here's the relevant passage](https://github.com/Genivia/RE-flex/blob/96d3b098da40fafa41675022d9e3f332c367b639/lib/pattern.cpp#L1258-L1269):

```cpp
static const char escapes[] = "__sSxX________hHdD__lL__uUwW";
s = std::strchr(escapes, c);
if (s != NULL)
{
  if (chars != NULL)
  {
    posix((s - escapes) / 2, *chars);
    if ((s - escapes) % 2)
      flip(*chars); //  <------- suspicious line
  }
  c = META_EOL;
}
```

When the letter is capitalized, the complement of the Unicode class is matched. This is expressed in the above code with `if ((s - escapes) % 2) flip(*chars);`. Except `chars` is not just the character class but potentially contains other characters as well. Shouldn't it only flip the characters in the character class? Why is it flipping all of `chars`?

**Comment by genivia-inc** [comment]
The `parse_escape` part here is for POSIX character classes only, as you guessed. Unicode is supported by a first pass over the regex with `Matcher::convert()`, see also `include/reflex/convert.h` and `lib/convert.cpp`. This converts and optimizes the regex to a string with UTF-8 characters (and UTF-8 character ranges or alternations) to speed up matching considerably, with no overhead for Unicode matching versus ASCII matching.

**Comment by rljacobson** [comment]
Great, I'll take a look. Thank you!
