### ISSUE TITLE
More easily use of RE/flex

### ISSUE THREAD

**Issue by yasushima-gd** [Genivia/RE-flex#83]
Could you use RE/flex for my program more easily?
For example, make an exception like Bison.

>As a special exception, you may create a larger work that contains part or all of the Bison parser skeleton and distribute that work under terms of your choice, so long as that work isn't itself a parser generator using the skeleton or a modified version thereof as a parser skeleton.
>Alternatively, if you modify or redistribute the parser skeleton itself, you may (at your option) remove this special exception, which will cause the skeleton and the resulting Bison output files to be licensed under the GNU General Public License without this special exception.

If I will use RE/flex generated lexer in my program, I also need to include RE/flex headers and libraries as sources.
However, since these are BSD licenses, copyright notice of RE/flex and license notice of BSD are required when publishing.
In addition, sources and headers of lexer generated by RE/flex have no license notice, so the license conditions are ambiguous.

Even if I try to spread the use of RE/flex, it's a indeed regrettable that the above license conditions hinder in some situations.

**Comment by genivia-inc** [comment]
Unlike GNU Bison that is licensed with the GPL, the BSD-3 clause license imposes minimal restrictions on the use and distribution of covered software.

From https://en.wikipedia.org/wiki/BSD_licenses:

_"This [BSD-3] version allows unlimited redistribution for any purpose as long as its copyright notices and the license's disclaimers of warranty are maintained. The license also contains a clause restricting use of the names of contributors for endorsement of a derived work without specific permission."_

**Comment by yasushima-gd** [comment]
To explain, now I'm trying to create an underlying library in my company. However, at my company, there are quite a few people who even troublesome the license notation.
So I'm looking for a lexer with the following requirements:

- Support UTF-16 input (to match Windows kernel)
- License notice not required

In the above requirements, re2c (public domain) is currently an option, but in my survey, RE/flex supports output in C++ class and has a lot of features, so I would like to use this if possible.

**Comment by genivia-inc** [comment]
The generated code is in essence unlicensed, because it is a transformed copy of the input (i.e. your lexer specification that you own). Hence, the generated code does not include or need license headers and does not enforce BSD-3.

The RE/flex header files (such as `reflex/flexlexer.h`) and the RE/flex library (`libreflex`) are BSD-3.

**Comment by yasushima-gd** [comment]
OK.
Thank you so much.
