### ISSUE TITLE
Are there any instructions/recipes/pointers for cross compiling Re/flex?

### ISSUE THREAD

**Issue by kk49** [Genivia/RE-flex#84]
I'd like to generate a lexer that would be built with emscripten for WebAssembly, are there any pointers/instructions for building the library with a different toolset than the generator?

**Comment by genivia-inc** [comment]
Any C++ compiler should work to get RE/flex compiled from the source. No need to build the library. A generated scanner `lex.yy.cpp` only needs the following support files located in the `lib` dir:
~~~
debug.cpp
error.cpp
input.cpp
matcher.cpp
pattern.cpp
utf8.cpp
~~~
and the source files located in the `include/reflex` dir should be accessible:
~~~
c++ -Ireflex/include lex.yy.cpp debug.cpp error.cpp input.cpp matcher.cpp pattern.cpp utf8.cpp ...
~~~

**Comment by kk49** [comment]
Perfect, thanks!

**Comment by genivia-inc** [comment]
I've added some brief instructions on this subject to the manual here: https://www.genivia.com/doc/reflex/html/#linking

If something is not clear then let me know.

**Comment by kk49** [comment]
Thanks, I'll give it a shot tomorrow and let you know how it goes.
