### ISSUE TITLE
lexer->buffer from string do not get last character

### ISSUE THREAD

**Issue by ClaudioDaffra** [Genivia/RE-flex#85]
example program

	%{
	// C++ example taken from the Flex documentation

	#include <stdio.h>
	#include <iostream>
	#include <reflex/flexlexer.h>
	#include <string.h>

	using namespace std ;

	int mylineno = 0;
	%}

	%option noyywrap

	string  \"[^\n"]+\"

	ws      [ \t]+

	alpha   [A-Za-z]
	dig     [0-9]
	name    ({alpha}|{dig}|\$)({alpha}|{dig}|[_.\-/$])*
	num1    [-+]?{dig}+\.?([eE][-+]?{dig}+)?
	num2    [-+]?{dig}*\.{dig}+([eE][-+]?{dig}+)?
	number  {num1}|{num2}

	%%

	{ws}    /* skip blanks and tabs */

	{number}  cout << "number " << YYText() << '\n';

	\n        mylineno++;

	{name}    cout << "name " << YYText() << '\n';

	{string}  cout << "string " << YYText() << '\n';

	%%

	int main(int argc, char *argv[])
	{
		printf("\n");

		FlexLexer* lexer = new yyFlexLexer;

		char *buffer = strdup("1 2 3 a b d") ;
		lexer->buffer(buffer,strlen(buffer)+1);

		while (lexer->yylex() != 0)
		;
		delete lexer;
	;		
		return 0;
	 
	}
		

result

	number 1
	number 2
	number 3
	name a
	name b

expected

	number 1
	number 2
	number 3
	name a
	name b
	name c <-- missing

patch

	I have to add +1 to strlen()

	lexer->buffer(buffer,strlen(buffer)+1);

**Comment by genivia-inc** [comment]
Please see the documentation that explains why: https://www.genivia.com/doc/reflex/html/index.html

Method | Result
------ | ------
`buffer(b, n)` | use buffer of `n` bytes at address `b` containing a string of `n`-1 bytes (zero copy)

And the warning:

So you will always have to pass buffer size+1. The last byte is needed for the terminating NUL to end the `text()` string that points to the buffer contents.
