### ISSUE TITLE
yyset_lineno() missing from Flex compatibility layer

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#88]
I use `set_lineno()` to support the equivalent of `#line N` preprocessor directives. It would be great if this could be added to `include/reflex/flexlexer.h`.

**Comment by genivia-inc** [comment]
I've added `yyset_lineno(n, s)` to `flexlexer.h` in v2.1.5 and a new matcher method `lineno(n)` to set or change the line number of the last match to `n`. There is a subtle implementation detail: these functions override the line number of the line with the last `text()` or `yytext` match, such that the next line (with a match) will be numbered `n + 1`.

**Comment by dnicolodi** [comment]
Great, thank you.

**Comment by dnicolodi** [comment]
Uhm. Unless I am doing something wrong, I think that the following declaration is missing from `abslexer.h`:
```
  /// Set or change the starting line number of the last match.
  inline void lineno(size_t n)
  {
    matcher().lineno(n);
  }
```
and that the define in `flexlexer.h` should be:
```
#define yyset_lineno(n,s)       static_cast<FlexLexer*>(s)->lineno(n)
```
without the extra `static_cast<int>` in the current definition. Also, it would be nice to have `yyset_lineno()` defined in the generated `flex.h` as for the other stubs I asked to be added a while ago for compatibility with Flex. I'll try to submit a patch soon.

**Comment by dnicolodi** [comment]
Please see the patch in #89
