### ISSUE TITLE
Simple UGrep Performance

### ISSUE THREAD

**Issue by BiBi-Abc** [Genivia/RE-flex#91]
I tried this Regex library out, and it's VERY simple to use! Thank you!

However, I am noticing poor performance with the ugrep.cpp included in the examples folder.

Here is what i did:

1. Download this repo
2. Copy everything in include and lib
3. Set up Visual Studio 2019 with max optimizations, etc. Making sure to add HAVE_AVX2
4. Copy ugrep.cpp
5. Test the performance. I used
```
Sherlock Holmes
```
on
http://opus.nlpl.eu/download.php?f=OpenSubtitles/v2018/mono/OpenSubtitles.raw.en.gz
uncompressed. The real ugrep managed around 1850MB/s on my disk while the simple ugrep only managed 800mb/s. Also, the fastsearch.cpp was faster then the simple UGrep at 1100MB/s, but not as fast as ugrep or my hyperscan grep implementation which could max out my disk.

Am I doing something wrong?

I also just wanted to say thanks for the super simple to use regex library.

**Comment by genivia-inc** [comment]
The simple ugrep application is not the fully optimized for grepping and is not meant to be so, because it is a stripped down demo on how to use the regex matcher as a grep tool. Also the RE/flex library isn't updated yet with the ugrep v3 improvements.

**Comment by genivia-inc** [comment]
Have you compared the speed to ripgrep by any chance?

**Comment by BiBi-Abc** [comment]
> 
> 
> Have you compared the speed to ripgrep by any chance?

Yes, I have. Ripgrep can get to 1700MB/s on my disk.



> 
> 
> The simple ugrep application is not fully optimized for grepping and is not meant to be so, because it is a stripped down demo on how to use the regex matcher as a grep tool. Also the RE/flex library isn't updated yet with the ugrep v3 improvements.

Also, I'm curious, how would I optimize the simple search? (fastsearch.cpp)
It's pretty simple, but other than swapping to `CreateFile`, and UGrep v3, what else would their be to get up to the real UGreps performance?

**Comment by BiBi-Abc** [comment]
God damn!!!
I copied over ugreps updated RE-Flex, moved it over to VS2019, built and run a very simple code:
```
reflex::Pattern pattern("Sherlock Holmes");
FILE* file = nullptr;
fopen_s(&file, "path\\to\\big\\file.txt", "rb");
reflex::Matcher matcher(pattern, reflex::Input(file));

while (matcher.find())
{
	
}

fclose(file);

```

and its hella fast! So simple as well! It gets to 1730MB/s, but I bet if I switch over to `CreateFile` which has no automatic buffering, I bet I can get up to 1850MB/s! Nearly as fast as my hyperscan implementation and MUCH easier aswell!

It also saved a bunch of valuable app space, AND has multiline support!!

Jees, thank you!

**Comment by BiBi-Abc** [comment]
I changed some of the settings, and now I can even beat my hyperscan implementation! I'm also going to change the Input class so that i

**Comment by genivia-inc** [comment]
RE/flex v3 is available with the redesigned engine that ugrep v3 already uses.

Thanks again for your feedback and comments!

**Comment by genivia-inc** [comment]
FYI a quick note: RE/flex v3 fixes a regression bug in v2.x when a specific pattern is used that produces an additional match, so you may want to upgrade to v3.
