### ISSUE TITLE
Handling of encodings other than UTF-8

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#94]
The handling of encodings other than UTF-8 is restricted to `FILE*` input. I was hoping that the same on-the-fly transcoding would work for `std::istream` inputs, but this does not seem the case. Is this something that can be implemented or there are technical reasons why it is not possible to re-use the same mechanisms?

**Comment by genivia-inc** [comment]
Support for `std::istream` UTF-16/32 input formats could be implemented with a derived class of `std::streambuf` to read another `std::istream` as input to produce a UTF-8 normalized `std::istream`. This should not be too hard to do, so perhaps someone has already done that as a general open source project? To do this on our end, the basics would be similar to the gzip decompressor `gz.l` example of RE/flex, but reading a `std::istream` to convert.

**Comment by dnicolodi** [comment]
I am not sure I explained clearly what I am after. Currently, it is possible to specify a `FILE*` input source along with a file encoding, with the 
```C++
  Input(
      FILE                 *file,        ///< input file
      file_encoding_type    enc,         ///< file_encoding (when UTF BOM is not present)
      const unsigned short *page = NULL) ///< code page for file_encoding::custom
```
constructor. In this case, IIUC, RE/flex internally transcodes the input from the specified encoding to UTF-8 expected by the scanner internals in the `Input::file_get()` method.

It would be great if this functionality could be exposed for `Input::Input(std::istream)` sources as well. It is possible to interpose the transcoding between the application and RE/flex, but this requires essentially duplicating code and codepages data that is already in RE/flex.

**Comment by genivia-inc** [comment]
Yes, that would be possible as I described with a derived class of `std::streambuf`. You just need to do this:

**Comment by genivia-inc** [comment]
This class is not part of RE/flex, but could be added in the future to normalize any `std::istream`. I will add this to the TODO list.
