### ISSUE TITLE
an option to output lex.yy.c to make RE-flex a drop-in replacement of flex?

### ISSUE THREAD

**Issue by staalmannen** [Genivia/RE-flex#96]
Hi I was just curious to know if this would be possible.

It would especially be interesting when makefiles call flex and expect lex.yy.c to be generated.

**Comment by genivia-inc** [comment]
The RE/flex tool is for C++. The generated files are C++. RE/flex is like the flex++ tool.

Working with Makefiles should not be a problem. See the examples included with RE/flex.
