### ISSUE TITLE
ReFlex does not allow spaces before the closing brace in states.

### ISSUE THREAD

**Issue by MichaelKv** [Genivia/RE-flex#97]
```
Hello. The following example does work with flex and it does not work with ReFlex:
%s A
%%
'a' BEGIN(A);

<A>{
.
 }
%%
ReFlex fails with “aaa.lex:8: error: EOF encountered inside scope A” error message. The workaround is to remove the space before } symblol.

**Comment by genivia-inc** [comment]
Leading spacing is not allowed for patterns and ending `}` of start condition scopes in RE/flex.

The problem is ambiguity with actions that are also indented. Because actions can flow to the next lines when indented, there is no reliable way to distinguish indented patterns in state condition scopes from actions.

Flex is a mess.

**Comment by genivia-inc** [comment]
One thing we can certainly do to allow pattern indentation in general is to set `%option freespace`, which works already and requires all code blocks to be bracketed with `{ }`. However, this should also allow the start condition scope ending to be specified as `}` with an arbitrary indent. That last requirement is not yet supported, but easy to add.

**Comment by MichaelKv** [comment]
Well, I can really remove spaces. It is not a big deal for me. Though it does not look like a too big problem to me as far as you need a limited look ahead to see if { is a start condition scope symbol or a pattern beginning (and it may not be an action after start rules). And this requires a proper ReFlex design indeed (I am not a big expert here).
But it is OK to continue to be a little messy as the original flex is. And it is up to you to be consistent with the original flex or not. Total majority of my lex files does not have a space before closing braces.

**Comment by genivia-inc** [comment]
Let me explain a little bit why Flex is a mess in this respect. Consider this example:
~~~
%%
PATTERN1 ACTION LINE 1
         ACTION LINE 2
         ACTION LINE 3
PATTERN2 ACTION LINE
%%
~~~
But this form of action indentation is not allowed in start condition scopes, giving errors (if you're lucky):
~~~
%%
<START> {
PATTERN1 ACTION LINE 1
         ACTION LINE 2
         ACTION LINE 3
PATTERN2 ACTION LINE
}
%%
~~~
Rather, now we must use brackets, like so:
~~~
%%
<START> {
PATTERN1 { ACTION LINE 1
         ACTION LINE 2
         ACTION LINE 3
}
PATTERN2 ACTION LINE
}
%%
~~~
This design appears broken to me. Not only is this ugly, it is forced and violates common principles of orthogonality in syntax designs.

A better approach is to allow action indentation in start condition scopes and disallow patterns to be indented.

With `%option freespace` the user can choose to use spaces in patterns and when to indent patterns. With this option all action code blocks should be bracketed.

Nice and clean.

**Comment by MichaelKv** [comment]
'''
> <START> {
You may not have the space before the brace here indeed in original flex.

>A better approach is to allow action indentation in start condition scopes and disallow patterns to be indented.
Personally I use indentation for patterns in complex start conditions as far as I prefer to use flex alone (without a parser generator) and use its stack to add some context-free features to it. So I prefer a complex flex for its writes and easy, flexible and convenient for its users.
It would be nice if the native ReFlex syntax (I have tried flex compatibility mode only so far) is more consistent and convenient than the original flex's one.

**Comment by genivia-inc** [comment]
I've made some improvements in v3.0.2.
